<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Console\Commands;

use App\Models\Autoresponder;
use App\Services\ImapConnection;
use App\Services\SmtpSender;
use Illuminate\Console\Command;

/**
 * Check IMAP inboxes for each active autoresponder and send replies.
 *
 * Schedule this via cron (every 5–15 minutes):
 *   * /5 * * * * php /var/www/opterius-mail/artisan mail:autorespond >> /dev/null 2>&1
 *
 * Requirements:
 *   - IMAP_MASTER_USER and IMAP_MASTER_PASS env vars (Dovecot master user)
 *   - OR the autoresponder account must share credentials with the IMAP server
 *     in a way that allows the command to authenticate as each address.
 *
 * Without master credentials, set MAIL_AUTORESPOND_PASSWORD in .env and run
 * autoresponders only for accounts whose password you store explicitly.
 */
class ProcessAutoresponders extends Command
{
    protected $signature   = 'mail:autorespond {--dry-run : Show what would be sent without sending}';
    protected $description = 'Process active autoresponders — send replies to new messages';

    public function handle(): int
    {
        $autoresponders = Autoresponder::where('is_active', true)->get()
            ->filter(fn($a) => $a->isCurrentlyActive());

        if ($autoresponders->isEmpty()) {
            $this->info('No active autoresponders.');
            return self::SUCCESS;
        }

        $masterUser = config('imap.master_user');
        $masterPass = config('imap.master_pass');

        if (!$masterUser || !$masterPass) {
            $this->warn('IMAP_MASTER_USER / IMAP_MASTER_PASS not set.');
            $this->warn('Cannot authenticate as individual accounts. See docs for setup.');
            return self::FAILURE;
        }

        $dryRun = $this->option('dry-run');
        $sent   = 0;

        foreach ($autoresponders as $ar) {
            $this->line("Processing: {$ar->email}");

            try {
                $messages = $this->fetchUnseen($ar->email, $masterUser, $masterPass);
            } catch (\Throwable $e) {
                $this->error("  IMAP error for {$ar->email}: {$e->getMessage()}");
                continue;
            }

            foreach ($messages as $msg) {
                $from = $msg['from']['email'] ?? '';

                if ($from === '' || $ar->alreadyRespondedTo($from)) {
                    continue;
                }

                // Avoid autoresponder loops
                if (str_contains(strtolower($from), 'noreply')
                    || str_contains(strtolower($from), 'no-reply')
                    || str_contains(strtolower($from), 'mailer-daemon')) {
                    continue;
                }

                $subject = $ar->subject ?: 'Re: ' . ($msg['subject'] ?? '');

                if ($dryRun) {
                    $this->line("  [dry-run] Would reply to {$from}: {$subject}");
                } else {
                    try {
                        (new SmtpSender())->send(
                            fromEmail: $ar->email,
                            fromName:  '',
                            password:  $masterPass,
                            to:        $from,
                            subject:   $subject,
                            bodyText:  $ar->body,
                        );
                        $ar->markRespondedTo($from);
                        $this->line("  Replied to {$from}");
                        $sent++;
                    } catch (\Throwable $e) {
                        $this->error("  SMTP error replying to {$from}: {$e->getMessage()}");
                    }
                }
            }
        }

        $this->info("Done. {$sent} autoresponse(s) sent.");
        return self::SUCCESS;
    }

    // ------------------------------------------------------------------

    /**
     * Fetch unseen messages for the given address using IMAP master credentials.
     */
    private function fetchUnseen(string $email, string $masterUser, string $masterPass): array
    {
        $imap = new ImapConnection();
        $imap->connect(
            host:         config('imap.host'),
            port:         config('imap.port'),
            encryption:   config('imap.encryption'),
            validateCert: config('imap.validate_cert', false),
            timeout:      config('imap.timeout', 15),
        );

        // Dovecot master user format: user*masteruser
        $imap->login("{$email}*{$masterUser}", $masterPass);
        $imap->selectFolder('INBOX');

        $uids = $imap->search('UNSEEN');

        if (empty($uids)) {
            $imap->logout();
            return [];
        }

        $headers  = $imap->fetchHeadersByUids(array_slice($uids, 0, 50));
        $imap->logout();

        return $headers;
    }
}
