<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Services;

use RuntimeException;

/**
 * Minimal pure-PHP IMAP client using stream sockets.
 * No ext-imap required. Implements enough of RFC 3501 for
 * authentication, folder listing, and message header fetching.
 */
class ImapConnection
{
    /** @var resource|null */
    private mixed $stream = null;
    private int $seq = 0;

    // ------------------------------------------------------------------
    // Connection lifecycle
    // ------------------------------------------------------------------

    public function connect(string $host, int $port, ?string $encryption, bool $validateCert = false, int $timeout = 10): void
    {
        $scheme = match (strtolower((string) $encryption)) {
            'ssl', 'tls', 'imaps' => 'ssl',
            default               => 'tcp',
        };

        $context = stream_context_create([
            'ssl' => [
                'verify_peer'       => $validateCert,
                'verify_peer_name'  => $validateCert,
                'allow_self_signed' => !$validateCert,
            ],
        ]);

        $address      = "{$scheme}://{$host}:{$port}";
        $this->stream = @stream_socket_client($address, $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $context);

        if (!$this->stream) {
            throw new RuntimeException("IMAP connect failed ({$host}:{$port}): {$errstr} [{$errno}]");
        }

        stream_set_timeout($this->stream, $timeout);

        $greeting = $this->readline();

        if (!str_starts_with((string) $greeting, '* OK') && !str_starts_with((string) $greeting, '* PREAUTH')) {
            $this->close();
            throw new RuntimeException("Unexpected IMAP greeting: {$greeting}");
        }

        if (strtolower((string) $encryption) === 'starttls') {
            ['ok' => $ok] = $this->command('STARTTLS');
            if (!$ok) {
                throw new RuntimeException('STARTTLS negotiation failed');
            }
            stream_socket_enable_crypto($this->stream, true, STREAM_CRYPTO_METHOD_TLS_CLIENT);
        }
    }

    public function login(string $username, string $password): bool
    {
        $u = '"' . addcslashes($username, '"\\') . '"';
        $p = '"' . addcslashes($password, '"\\') . '"';
        return $this->command("LOGIN {$u} {$p}")['ok'];
    }

    public function logout(): void
    {
        if ($this->stream) {
            try {
                $this->command('LOGOUT');
            } catch (\Throwable) {
            }
            $this->close();
        }
    }

    // ------------------------------------------------------------------
    // High-level mailbox operations
    // ------------------------------------------------------------------

    /**
     * LIST all selectable folders.
     *
     * @return array<array{name: string, attributes: string[], delimiter: string}>
     */
    public function listFolders(string $ref = '', string $pattern = '*'): array
    {
        $r      = '"' . addcslashes($ref, '"\\') . '"';
        $p      = '"' . addcslashes($pattern, '"\\') . '"';
        $result = $this->command("LIST {$r} {$p}");

        $folders = [];
        foreach ($result['untagged'] as $line) {
            // * LIST (\attributes) "delimiter" "folder-name"  OR  atom
            if (!preg_match('/^\* LIST \(([^)]*)\) (\S+) (.+)$/i', $line, $m)) {
                continue;
            }

            $attrs = array_values(array_filter(explode(' ', strtolower(trim($m[1])))));
            $name  = trim($m[3], '"');

            // Skip non-selectable containers (\Noselect)
            if (in_array('\\noselect', $attrs, true)) {
                continue;
            }

            $folders[] = [
                'name'       => $name,
                'attributes' => $attrs,
                'delimiter'  => trim($m[2], '"'),
            ];
        }

        // INBOX first, then alphabetical
        usort($folders, static function (array $a, array $b): int {
            if (strtoupper($a['name']) === 'INBOX') {
                return -1;
            }
            if (strtoupper($b['name']) === 'INBOX') {
                return 1;
            }
            return strcasecmp($a['name'], $b['name']);
        });

        return $folders;
    }

    /**
     * Create a new IMAP mailbox.
     */
    public function createFolder(string $name): bool
    {
        $n = '"' . addcslashes($name, '"\\') . '"';
        return $this->command("CREATE {$n}")['ok'];
    }

    /**
     * Rename an existing IMAP mailbox.
     */
    public function renameFolder(string $from, string $to): bool
    {
        $f = '"' . addcslashes($from, '"\\') . '"';
        $t = '"' . addcslashes($to, '"\\') . '"';
        return $this->command("RENAME {$f} {$t}")['ok'];
    }

    /**
     * Delete an IMAP mailbox.
     * The mailbox must be empty (no messages) on most servers.
     */
    public function deleteFolder(string $name): bool
    {
        $n = '"' . addcslashes($name, '"\\') . '"';
        return $this->command("DELETE {$n}")['ok'];
    }

    /**
     * Get MESSAGES and UNSEEN counts for a folder without selecting it.
     *
     * @return array{messages: int, unseen: int}
     */
    public function getFolderStatus(string $folder): array
    {
        $f      = '"' . addcslashes($folder, '"\\') . '"';
        $result = $this->command("STATUS {$f} (MESSAGES UNSEEN)");

        $stats = ['messages' => 0, 'unseen' => 0];
        foreach ($result['untagged'] as $line) {
            if (preg_match('/\bMESSAGES (\d+)/i', $line, $m)) {
                $stats['messages'] = (int) $m[1];
            }
            if (preg_match('/\bUNSEEN (\d+)/i', $line, $m)) {
                $stats['unseen'] = (int) $m[1];
            }
        }
        return $stats;
    }

    /**
     * SELECT a mailbox and return basic stats.
     * Must be called before fetchMessageHeaders().
     *
     * @return array{exists: int, uidvalidity: int, uidnext: int}
     */
    public function selectFolder(string $folder): array
    {
        $f      = '"' . addcslashes($folder, '"\\') . '"';
        $result = $this->command("SELECT {$f}");

        $stats = ['exists' => 0, 'uidvalidity' => 0, 'uidnext' => 0];
        foreach ($result['untagged'] as $line) {
            if (preg_match('/^\* (\d+) EXISTS/i', $line, $m)) {
                $stats['exists'] = (int) $m[1];
            } elseif (preg_match('/\[UIDVALIDITY (\d+)\]/i', $line, $m)) {
                $stats['uidvalidity'] = (int) $m[1];
            } elseif (preg_match('/\[UIDNEXT (\d+)\]/i', $line, $m)) {
                $stats['uidnext'] = (int) $m[1];
            }
        }

        return $stats;
    }

    /**
     * Fetch the full raw RFC 2822 message for a UID.
     * Does NOT set the \Seen flag (uses BODY.PEEK).
     * Call markSeen() separately after confirming the fetch succeeded.
     *
     * @return array{raw: string, flags: string[]}
     */
    public function fetchMessageRaw(int $uid): array
    {
        $result = $this->command("UID FETCH {$uid} (FLAGS BODY.PEEK[])");

        foreach ($result['untagged'] as $line) {
            if (!preg_match('/^\* \d+ FETCH /i', $line)) {
                continue;
            }

            $flags = [];
            if (preg_match('/\bFLAGS \(([^)]*)\)/i', $line, $m)) {
                $flags = array_values(array_filter(explode(' ', trim($m[1]))));
            }

            if (preg_match('/\{(\d+)\}\r\n/', $line, $lm, PREG_OFFSET_CAPTURE)) {
                $n         = (int) $lm[1][0];
                $dataStart = (int) $lm[0][1] + strlen($lm[0][0]);
                return [
                    'raw'   => substr($line, $dataStart, $n),
                    'flags' => $flags,
                ];
            }
        }

        return ['raw' => '', 'flags' => []];
    }

    /**
     * Mark a message as read by adding the \Seen flag.
     */
    public function markSeen(int $uid): void
    {
        $this->command("UID STORE {$uid} +FLAGS (\\Seen)");
    }

    /**
     * Fetch message headers for a sequence range (e.g. "101:150").
     * Must call selectFolder() first.
     *
     * Returns messages newest-first. Each entry:
     *   seq, uid, flags[], seen, flagged, from{name,email}, subject, date_raw
     *
     * @return array<array{seq: int, uid: int, flags: string[], seen: bool, flagged: bool, from: array{name: string, email: string}, subject: string, date_raw: string}>
     */
    public function fetchMessageHeaders(string $sequence): array
    {
        $result = $this->command(
            "FETCH {$sequence} (UID FLAGS BODY.PEEK[HEADER.FIELDS (FROM SUBJECT DATE)])"
        );

        $messages = [];

        foreach ($result['untagged'] as $line) {
            if (!preg_match('/^\* (\d+) FETCH /i', $line, $sm)) {
                continue;
            }
            $seq = (int) $sm[1];

            // UID
            $uid = 0;
            if (preg_match('/\bUID (\d+)/i', $line, $m)) {
                $uid = (int) $m[1];
            }

            // FLAGS
            $flags = [];
            if (preg_match('/\bFLAGS \(([^)]*)\)/i', $line, $m)) {
                $flags = array_values(array_filter(explode(' ', trim($m[1]))));
            }

            // Extract header block using the literal length: {N}\r\n<N bytes>
            $rawHeaders = '';
            if (preg_match('/\{(\d+)\}\r\n/', $line, $lm, PREG_OFFSET_CAPTURE)) {
                $n          = (int) $lm[1][0];
                $dataStart  = (int) $lm[0][1] + strlen($lm[0][0]);
                $rawHeaders = substr($line, $dataStart, $n);
            }

            $messages[$seq] = [
                'seq'      => $seq,
                'uid'      => $uid,
                'flags'    => $flags,
                'seen'     => in_array('\\Seen', $flags, true),
                'flagged'  => in_array('\\Flagged', $flags, true),
                'from'     => $this->parseFrom($this->decodeMimeHeader($this->parseHeader($rawHeaders, 'From'))),
                'subject'  => $this->decodeMimeHeader($this->parseHeader($rawHeaders, 'Subject')) ?: '(no subject)',
                'date_raw' => $this->parseHeader($rawHeaders, 'Date'),
            ];
        }

        // Newest first (highest seq = most recent message)
        krsort($messages);

        return array_values($messages);
    }

    /**
     * Search for messages matching IMAP search criteria.
     * Must call selectFolder() first.
     * Returns UIDs sorted newest-first (highest UID first).
     *
     * Example criteria: 'OR SUBJECT "hello" FROM "hello"'
     *
     * @return int[]
     */
    public function search(string $criteria): array
    {
        $result = $this->command("UID SEARCH {$criteria}");

        $uids = [];
        foreach ($result['untagged'] as $line) {
            if (str_starts_with($line, '* SEARCH')) {
                $part = trim(substr($line, strlen('* SEARCH')));
                if ($part !== '') {
                    $uids = array_values(array_map('intval', explode(' ', $part)));
                }
                break;
            }
        }

        rsort($uids);   // highest UID = most recent message
        return $uids;
    }

    /**
     * Fetch message headers for an explicit list of UIDs.
     * Must call selectFolder() first.
     *
     * Returns messages in the same order as $uids (caller controls ordering).
     *
     * @param  int[] $uids
     * @return array<array{seq: int, uid: int, flags: string[], seen: bool, flagged: bool, from: array{name: string, email: string}, subject: string, date_raw: string}>
     */
    public function fetchHeadersByUids(array $uids): array
    {
        if (empty($uids)) {
            return [];
        }

        $uidList = implode(',', $uids);
        $result  = $this->command(
            "UID FETCH {$uidList} (UID FLAGS BODY.PEEK[HEADER.FIELDS (FROM SUBJECT DATE)])"
        );

        $byUid = [];

        foreach ($result['untagged'] as $line) {
            if (!preg_match('/^\* (\d+) FETCH /i', $line, $sm)) {
                continue;
            }
            $seq = (int) $sm[1];

            $uid = 0;
            if (preg_match('/\bUID (\d+)/i', $line, $m)) {
                $uid = (int) $m[1];
            }

            $flags = [];
            if (preg_match('/\bFLAGS \(([^)]*)\)/i', $line, $m)) {
                $flags = array_values(array_filter(explode(' ', trim($m[1]))));
            }

            $rawHeaders = '';
            if (preg_match('/\{(\d+)\}\r\n/', $line, $lm, PREG_OFFSET_CAPTURE)) {
                $n          = (int) $lm[1][0];
                $dataStart  = (int) $lm[0][1] + strlen($lm[0][0]);
                $rawHeaders = substr($line, $dataStart, $n);
            }

            $byUid[$uid] = [
                'seq'      => $seq,
                'uid'      => $uid,
                'flags'    => $flags,
                'seen'     => in_array('\\Seen', $flags, true),
                'flagged'  => in_array('\\Flagged', $flags, true),
                'from'     => $this->parseFrom($this->decodeMimeHeader($this->parseHeader($rawHeaders, 'From'))),
                'subject'  => $this->decodeMimeHeader($this->parseHeader($rawHeaders, 'Subject')) ?: '(no subject)',
                'date_raw' => $this->parseHeader($rawHeaders, 'Date'),
            ];
        }

        // Return in the caller-supplied UID order
        $ordered = [];
        foreach ($uids as $uid) {
            if (isset($byUid[$uid])) {
                $ordered[] = $byUid[$uid];
            }
        }

        return $ordered;
    }

    // ------------------------------------------------------------------
    // Raw protocol helpers
    // ------------------------------------------------------------------

    /**
     * Send a tagged command and collect all lines until the tagged response.
     * Uses readResponse() which transparently expands IMAP literals.
     */
    public function command(string $cmd): array
    {
        $tag = $this->nextTag();
        fwrite($this->stream, "{$tag} {$cmd}\r\n");

        $untagged = [];
        $status   = null;

        while (true) {
            $raw = $this->readResponse();

            if ($raw === null) {
                break;
            }

            if (str_starts_with($raw, "{$tag} ")) {
                $status = $raw;
                break;
            }

            $untagged[] = $raw;
        }

        $ok = $status !== null && str_starts_with($status, "{$tag} OK");

        return [
            'ok'       => $ok,
            'status'   => $status,
            'untagged' => $untagged,
        ];
    }

    /** Read a single line from the stream (CRLF stripped). */
    public function readline(): ?string
    {
        if (!$this->stream) {
            return null;
        }
        $line = fgets($this->stream, 65536);
        if ($line === false) {
            return null;
        }
        return rtrim($line, "\r\n");
    }

    /**
     * Read a complete IMAP response, expanding inline literals.
     * When a line ends in {N}, reads exactly N more bytes then the next line.
     */
    private function readResponse(): ?string
    {
        $line = $this->readline();
        if ($line === null) {
            return null;
        }

        // Expand IMAP literals: {N} at end of line → read N bytes + continuation
        while (preg_match('/\{(\d+)\}$/', $line, $m)) {
            $n    = (int) $m[1];
            $data = $this->readBytes($n);
            $next = $this->readline();
            $line = $line . "\r\n" . $data . ($next ?? '');
        }

        return $line;
    }

    /** Read exactly $n bytes from the stream. */
    private function readBytes(int $n): string
    {
        $buf = '';
        while (strlen($buf) < $n) {
            $chunk = fread($this->stream, $n - strlen($buf));
            if ($chunk === false || $chunk === '') {
                break;
            }
            $buf .= $chunk;
        }
        return $buf;
    }

    /** Write raw data to the stream (for APPEND, literal commands, etc.). */
    public function write(string $data): void
    {
        fwrite($this->stream, $data);
    }

    public function isConnected(): bool
    {
        return $this->stream !== null && !feof($this->stream);
    }

    public function close(): void
    {
        if ($this->stream) {
            fclose($this->stream);
            $this->stream = null;
        }
        $this->seq = 0;
    }

    private function nextTag(): string
    {
        return 'A' . str_pad((string) ++$this->seq, 4, '0', STR_PAD_LEFT);
    }

    // ------------------------------------------------------------------
    // Header parsing helpers
    // ------------------------------------------------------------------

    /**
     * Extract a single header value from a raw header block.
     * Handles folded (multi-line) headers per RFC 2822.
     */
    private function parseHeader(string $raw, string $name): string
    {
        if (preg_match(
            '/^' . preg_quote($name, '/') . ':\s*(.*(?:\r?\n[ \t].+)*)/mi',
            $raw,
            $m
        )) {
            // Unfold: collapse CRLF + leading whitespace into a single space
            return trim(preg_replace('/\r?\n[ \t]+/', ' ', $m[1]) ?? '');
        }
        return '';
    }

    /**
     * Parse a From header value into name + email.
     *
     * @return array{name: string, email: string}
     */
    private function parseFrom(string $from): array
    {
        $from = trim($from);
        if ($from === '') {
            return ['name' => '', 'email' => ''];
        }

        // "Display Name" <email>  or  Display Name <email>
        if (preg_match('/^"?(.+?)"?\s*<([^>]+)>$/', $from, $m)) {
            return ['name' => trim($m[1], ' "'), 'email' => trim($m[2])];
        }

        // <email>
        if (preg_match('/^<([^>]+)>$/', $from, $m)) {
            return ['name' => $m[1], 'email' => $m[1]];
        }

        // Bare email or name
        return ['name' => $from, 'email' => $from];
    }

    /**
     * Decode MIME-encoded header value (=?charset?B/Q?...?=).
     */
    private function decodeMimeHeader(string $value): string
    {
        if ($value === '') {
            return '';
        }

        if (function_exists('mb_decode_mimeheader')) {
            return mb_decode_mimeheader($value);
        }

        // Fallback: decode =?charset?B|Q?text?= sequences manually
        return preg_replace_callback(
            '/=\?([^?]+)\?([BQbq])\?([^?]*)\?=/',
            static function (array $m): string {
                $charset  = $m[1];
                $encoding = strtoupper($m[2]);
                $text     = $m[3];
                $decoded  = $encoding === 'B'
                    ? base64_decode($text)
                    : quoted_printable_decode(str_replace('_', ' ', $text));
                return mb_convert_encoding($decoded, 'UTF-8', $charset);
            },
            $value
        ) ?? $value;
    }
}
