<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Services;

use RuntimeException;

/**
 * Minimal pure-PHP IMAP client using stream sockets.
 * No ext-imap required. Implements enough of RFC 3501 for
 * authentication and basic mailbox operations.
 */
class ImapConnection
{
    /** @var resource|null */
    private mixed $stream = null;
    private int $seq = 0;

    public function connect(string $host, int $port, ?string $encryption, bool $validateCert = false, int $timeout = 10): void
    {
        $scheme = match (strtolower((string) $encryption)) {
            'ssl'           => 'ssl',
            'tls', 'imaps' => 'ssl',
            default         => 'tcp',
        };

        $context = stream_context_create([
            'ssl' => [
                'verify_peer'       => $validateCert,
                'verify_peer_name'  => $validateCert,
                'allow_self_signed' => !$validateCert,
            ],
        ]);

        $address      = "{$scheme}://{$host}:{$port}";
        $this->stream = @stream_socket_client($address, $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $context);

        if (!$this->stream) {
            throw new RuntimeException("IMAP connect failed ({$host}:{$port}): {$errstr} [{$errno}]");
        }

        stream_set_timeout($this->stream, $timeout);

        $greeting = $this->readline();

        if (!str_starts_with($greeting, '* OK') && !str_starts_with($greeting, '* PREAUTH')) {
            $this->close();
            throw new RuntimeException("Unexpected IMAP greeting: {$greeting}");
        }

        if (strtolower((string) $encryption) === 'starttls') {
            ['ok' => $ok] = $this->command('STARTTLS');
            if (!$ok) {
                throw new RuntimeException('STARTTLS negotiation failed');
            }
            stream_socket_enable_crypto($this->stream, true, STREAM_CRYPTO_METHOD_TLS_CLIENT);
        }
    }

    public function login(string $username, string $password): bool
    {
        $u = '"' . addcslashes($username, '"\\') . '"';
        $p = '"' . addcslashes($password, '"\\') . '"';
        return $this->command("LOGIN {$u} {$p}")['ok'];
    }

    public function logout(): void
    {
        if ($this->stream) {
            try {
                $this->command('LOGOUT');
            } catch (\Throwable) {
            }
            $this->close();
        }
    }

    // ------------------------------------------------------------------
    // Raw protocol helpers
    // ------------------------------------------------------------------

    /** Send a tagged command and collect lines until the tagged response. */
    public function command(string $cmd): array
    {
        $tag  = $this->nextTag();
        $line = "{$tag} {$cmd}\r\n";
        fwrite($this->stream, $line);

        $untagged = [];
        $status   = null;

        while (true) {
            $raw = $this->readline();

            if ($raw === null) {
                break;
            }

            if (str_starts_with($raw, "{$tag} ")) {
                $status = $raw;
                break;
            }

            $untagged[] = $raw;
        }

        $ok = $status !== null && str_starts_with($status, "{$tag} OK");

        return [
            'ok'       => $ok,
            'status'   => $status,
            'untagged' => $untagged,
        ];
    }

    /** Read a single line from the stream. */
    public function readline(): ?string
    {
        if (!$this->stream) {
            return null;
        }
        $line = fgets($this->stream, 65536);
        if ($line === false) {
            return null;
        }
        return rtrim($line, "\r\n");
    }

    /** Write raw data to the stream. */
    public function write(string $data): void
    {
        fwrite($this->stream, $data);
    }

    public function isConnected(): bool
    {
        return $this->stream !== null && !feof($this->stream);
    }

    public function close(): void
    {
        if ($this->stream) {
            fclose($this->stream);
            $this->stream = null;
        }
        $this->seq = 0;
    }

    private function nextTag(): string
    {
        return 'A' . str_pad((string) ++$this->seq, 4, '0', STR_PAD_LEFT);
    }
}
