<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Services;

use RuntimeException;

/**
 * Minimal ManageSieve client (RFC 5804).
 * Connects via TCP to port 4190, authenticates with PLAIN SASL,
 * and supports get/put/activate/delete of Sieve scripts.
 */
class ManageSieveConnection
{
    /** @var resource|null */
    private mixed $stream = null;

    // ------------------------------------------------------------------

    public function connect(string $host, int $port = 4190, int $timeout = 10): void
    {
        $ctx          = stream_context_create(['ssl' => ['verify_peer' => false, 'verify_peer_name' => false]]);
        $this->stream = @stream_socket_client("tcp://{$host}:{$port}", $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $ctx);

        if (!$this->stream) {
            throw new RuntimeException("ManageSieve connect failed ({$host}:{$port}): {$errstr} [{$errno}]");
        }

        stream_set_timeout($this->stream, $timeout);

        // Read capability greeting
        $this->readResponse();
    }

    /**
     * Authenticate with PLAIN SASL.
     */
    public function login(string $username, string $password): void
    {
        $plain = base64_encode("\0{$username}\0{$password}");
        $this->command("AUTHENTICATE \"PLAIN\" \"{$plain}\"");
    }

    /**
     * List all scripts: returns array of ['name' => ..., 'active' => bool].
     *
     * @return array<array{name: string, active: bool}>
     */
    public function listScripts(): array
    {
        $response = $this->command('LISTSCRIPTS');
        $scripts  = [];

        foreach ($response as $line) {
            if (preg_match('/^"([^"]+)"(\s+ACTIVE)?$/i', trim($line), $m)) {
                $scripts[] = [
                    'name'   => $m[1],
                    'active' => isset($m[2]) && strtoupper(trim($m[2])) === 'ACTIVE',
                ];
            }
        }

        return $scripts;
    }

    /**
     * Retrieve a script's content by name.
     */
    public function getScript(string $name): string
    {
        $response = $this->command('GETSCRIPT ' . $this->quote($name));
        // Response lines include the script content after the size literal
        return implode("\r\n", $response);
    }

    /**
     * Upload (create or replace) a script.
     */
    public function putScript(string $name, string $content): void
    {
        $normalized = preg_replace("/\r\n|\r|\n/", "\r\n", $content);
        $bytes      = strlen($normalized);
        $this->sendRaw('PUTSCRIPT ' . $this->quote($name) . " {{$bytes}}\r\n");
        $this->sendRaw($normalized . "\r\n");
        $this->readResponse();
    }

    /**
     * Activate a script by name.
     */
    public function setActive(string $name): void
    {
        $this->command('SETACTIVE ' . $this->quote($name));
    }

    /**
     * Delete a script by name.
     */
    public function deleteScript(string $name): void
    {
        $this->command('DELETESCRIPT ' . $this->quote($name));
    }

    public function logout(): void
    {
        if ($this->stream) {
            try {
                $this->sendRaw("LOGOUT\r\n");
            } catch (\Throwable) {}
            $this->close();
        }
    }

    public function close(): void
    {
        if ($this->stream) {
            fclose($this->stream);
            $this->stream = null;
        }
    }

    // ------------------------------------------------------------------

    private function command(string $cmd): array
    {
        $this->sendRaw($cmd . "\r\n");
        return $this->readResponse();
    }

    private function sendRaw(string $data): void
    {
        fwrite($this->stream, $data);
    }

    /**
     * Read response lines until OK/NO/BYE tagged response.
     */
    private function readResponse(): array
    {
        $lines = [];

        while (true) {
            $line = fgets($this->stream, 65536);
            if ($line === false) {
                break;
            }
            $line = rtrim($line, "\r\n");

            if (preg_match('/^(OK|NO|BYE)/i', $line, $m)) {
                if (strtoupper($m[1]) === 'NO') {
                    throw new RuntimeException("ManageSieve error: {$line}");
                }
                break;
            }

            // Literal: {N+} or {N}
            if (preg_match('/^\{(\d+)\+?\}$/', $line, $m)) {
                $n       = (int) $m[1];
                $content = '';
                while (strlen($content) < $n) {
                    $chunk = fread($this->stream, $n - strlen($content));
                    if ($chunk === false || $chunk === '') {
                        break;
                    }
                    $content .= $chunk;
                }
                $lines[] = $content;
                continue;
            }

            $lines[] = $line;
        }

        return $lines;
    }

    private function quote(string $s): string
    {
        return '"' . addcslashes($s, '"\\') . '"';
    }
}
