<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Services;

/**
 * Minimal RFC 2822 / MIME email parser.
 * Handles plain-text, HTML, multipart/alternative and multipart/mixed emails.
 * No external extensions required.
 */
class MimeParser
{
    /**
     * Parse a raw RFC 2822 message into a structured array.
     *
     * @return array{
     *   from: array{name: string, email: string},
     *   to: array<array{name: string, email: string}>,
     *   cc: array<array{name: string, email: string}>,
     *   subject: string,
     *   date_raw: string,
     *   body_html: string,
     *   body_text: string,
     *   has_attachments: bool,
     * }
     */
    public function parse(string $raw): array
    {
        [$headerBlock, $body] = $this->splitHeadersBody($raw);
        $headers = $this->parseHeaderBlock($headerBlock);

        $result = [
            'from'            => $this->parseSingleAddress($this->decodeHeader($headers['from'] ?? '')),
            'to'              => $this->parseAddressList($this->decodeHeader($headers['to'] ?? '')),
            'cc'              => $this->parseAddressList($this->decodeHeader($headers['cc'] ?? '')),
            'subject'         => $this->decodeHeader($headers['subject'] ?? '') ?: '(no subject)',
            'date_raw'        => $headers['date'] ?? '',
            'body_html'       => '',
            'body_text'       => '',
            'has_attachments' => false,
        ];

        $contentType = $headers['content-type'] ?? 'text/plain';
        $encoding    = strtolower(trim($headers['content-transfer-encoding'] ?? '7bit'));

        $this->extractBody($contentType, $encoding, $body, $result);

        return $result;
    }

    // ------------------------------------------------------------------
    // Body extraction
    // ------------------------------------------------------------------

    private function extractBody(string $contentType, string $encoding, string $body, array &$result): void
    {
        $ct = strtolower($contentType);

        if (str_starts_with($ct, 'multipart/')) {
            $boundary = $this->getBoundary($contentType);
            if ($boundary === '') {
                return;
            }
            foreach ($this->splitMultipart($body, $boundary) as $part) {
                [$ph, $pb]    = $this->splitHeadersBody(ltrim($part, "\r\n"));
                $headers      = $this->parseHeaderBlock($ph);
                $pct          = $headers['content-type'] ?? 'text/plain';
                $penc         = strtolower(trim($headers['content-transfer-encoding'] ?? '7bit'));
                $disposition  = strtolower($headers['content-disposition'] ?? '');

                if (str_starts_with($disposition, 'attachment')) {
                    $result['has_attachments'] = true;
                    continue;
                }

                // Recurse into nested multipart
                if (str_starts_with(strtolower($pct), 'multipart/')) {
                    $this->extractBody($pct, $penc, $pb, $result);
                    continue;
                }

                $decoded = $this->decodeBody($pb, $penc, $pct);

                if (str_starts_with(strtolower($pct), 'text/html') && $result['body_html'] === '') {
                    $result['body_html'] = $decoded;
                } elseif (str_starts_with(strtolower($pct), 'text/plain') && $result['body_text'] === '') {
                    $result['body_text'] = $decoded;
                }
            }
            return;
        }

        $decoded = $this->decodeBody($body, $encoding, $contentType);

        if (str_starts_with(strtolower($ct), 'text/html')) {
            $result['body_html'] = $decoded;
        } else {
            $result['body_text'] = $decoded;
        }
    }

    // ------------------------------------------------------------------
    // Body decoding
    // ------------------------------------------------------------------

    private function decodeBody(string $body, string $encoding, string $contentType): string
    {
        $decoded = match ($encoding) {
            'base64'            => base64_decode(preg_replace('/\s+/', '', $body) ?? ''),
            'quoted-printable'  => quoted_printable_decode($body),
            default             => $body,
        };

        if ($decoded === false) {
            $decoded = $body;
        }

        // Convert charset to UTF-8
        $charset = $this->getCharset($contentType);
        if ($charset !== '' && strtoupper($charset) !== 'UTF-8') {
            $converted = @mb_convert_encoding($decoded, 'UTF-8', $charset);
            if ($converted !== false && $converted !== '') {
                $decoded = $converted;
            }
        }

        return $decoded;
    }

    // ------------------------------------------------------------------
    // Multipart splitting
    // ------------------------------------------------------------------

    private function splitMultipart(string $body, string $boundary): array
    {
        $delim  = '--' . $boundary;
        $parts  = [];
        $lines  = explode("\n", str_replace("\r\n", "\n", $body));
        $current = null;

        foreach ($lines as $line) {
            $trimmed = rtrim($line);
            if ($trimmed === $delim || $trimmed === $delim . '--') {
                if ($current !== null) {
                    $parts[] = implode("\n", $current);
                }
                if ($trimmed === $delim . '--') {
                    break;
                }
                $current = [];
            } elseif ($current !== null) {
                $current[] = $line;
            }
        }

        return array_filter($parts, static fn(string $p): bool => trim($p) !== '');
    }

    // ------------------------------------------------------------------
    // Header parsing
    // ------------------------------------------------------------------

    /**
     * Split a raw message into [headerBlock, body].
     */
    private function splitHeadersBody(string $raw): array
    {
        // Try CRLF first, then LF-only
        foreach (["\r\n\r\n", "\n\n"] as $sep) {
            $pos = strpos($raw, $sep);
            if ($pos !== false) {
                return [
                    substr($raw, 0, $pos),
                    substr($raw, $pos + strlen($sep)),
                ];
            }
        }
        return [$raw, ''];
    }

    /**
     * Parse a header block into a lowercase-keyed associative array.
     * Handles folded (multi-line) headers.
     */
    private function parseHeaderBlock(string $block): array
    {
        // Unfold folded headers (continuation lines start with whitespace)
        $block   = preg_replace('/\r?\n[ \t]+/', ' ', $block) ?? $block;
        $headers = [];

        foreach (explode("\n", str_replace("\r\n", "\n", $block)) as $line) {
            $colon = strpos($line, ':');
            if ($colon !== false) {
                $name  = strtolower(trim(substr($line, 0, $colon)));
                $value = trim(substr($line, $colon + 1));
                // Keep only first occurrence (RFC 2822: most headers are unique)
                if (!isset($headers[$name])) {
                    $headers[$name] = $value;
                }
            }
        }

        return $headers;
    }

    // ------------------------------------------------------------------
    // Address parsing
    // ------------------------------------------------------------------

    /**
     * @return array<array{name: string, email: string}>
     */
    private function parseAddressList(string $raw): array
    {
        if (trim($raw) === '') {
            return [];
        }

        // Split on commas that are NOT inside angle brackets
        $addresses = preg_split('/,(?![^<]*>)/', $raw) ?: [$raw];

        return array_values(array_filter(
            array_map(fn(string $a) => $this->parseSingleAddress(trim($a)), $addresses),
            static fn(array $a): bool => $a['email'] !== '',
        ));
    }

    /**
     * @return array{name: string, email: string}
     */
    private function parseSingleAddress(string $addr): array
    {
        $addr = trim($addr);

        // "Display Name" <email>  or  Display Name <email>
        if (preg_match('/^"?(.+?)"?\s*<([^>]+)>$/', $addr, $m)) {
            return ['name' => trim($m[1], ' "'), 'email' => trim($m[2])];
        }
        // <email>
        if (preg_match('/^<([^>]+)>$/', $addr, $m)) {
            return ['name' => '', 'email' => trim($m[1])];
        }
        // Bare email address
        if (str_contains($addr, '@')) {
            return ['name' => '', 'email' => $addr];
        }

        return ['name' => $addr, 'email' => ''];
    }

    // ------------------------------------------------------------------
    // MIME header decoding
    // ------------------------------------------------------------------

    private function decodeHeader(string $value): string
    {
        if ($value === '') {
            return '';
        }
        if (function_exists('mb_decode_mimeheader')) {
            return mb_decode_mimeheader($value);
        }
        return preg_replace_callback(
            '/=\?([^?]+)\?([BQbq])\?([^?]*)\?=/',
            static function (array $m): string {
                $decoded = strtoupper($m[2]) === 'B'
                    ? base64_decode($m[3])
                    : quoted_printable_decode(str_replace('_', ' ', $m[3]));
                return (string) @mb_convert_encoding((string) $decoded, 'UTF-8', $m[1]);
            },
            $value,
        ) ?? $value;
    }

    // ------------------------------------------------------------------
    // Content-Type parameter helpers
    // ------------------------------------------------------------------

    private function getBoundary(string $contentType): string
    {
        if (preg_match('/boundary\s*=\s*"?([^";,\s]+)"?/i', $contentType, $m)) {
            return $m[1];
        }
        return '';
    }

    private function getCharset(string $contentType): string
    {
        if (preg_match('/charset\s*=\s*"?([^";,\s]+)"?/i', $contentType, $m)) {
            return $m[1];
        }
        return '';
    }
}
