<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Services;

use Illuminate\Http\UploadedFile;
use Symfony\Component\Mailer\Mailer as SymfonyMailer;
use Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email;

/**
 * Sends email on behalf of the authenticated webmail user via SMTP.
 * Credentials come from the IMAP session (same login/password).
 */
class SmtpSender
{
    /**
     * Send a message. Returns the raw RFC 5322 message bytes so callers can
     * APPEND a copy to the user's Sent folder via IMAP.
     *
     * $authUsername lets SSO sessions submit using the Dovecot master-user
     * format ("user@domain*master-user") with the master password, while the
     * From: address remains the plain user email.
     *
     * @throws \Throwable on SMTP or addressing errors
     */
    /**
     * @param UploadedFile[] $attachments
     */
    public function send(
        string $fromEmail,
        string $fromName,
        string $password,
        string $to,
        string $subject = '',
        string $bodyText = '',
        string $bodyHtml = '',
        string $cc = '',
        string $bcc = '',
        string $authUsername = '',
        array  $attachments = [],
    ): string {
        $transport = $this->buildTransport(
            $authUsername !== '' ? $authUsername : $fromEmail,
            $password,
        );

        $email = (new Email())
            ->from(new Address($fromEmail, $fromName ?: $fromEmail))
            ->subject($subject !== '' ? $subject : '(no subject)');

        foreach ($this->parseAddresses($to) as $addr) {
            $email->addTo($addr);
        }
        foreach ($this->parseAddresses($cc) as $addr) {
            $email->addCc($addr);
        }
        foreach ($this->parseAddresses($bcc) as $addr) {
            $email->addBcc($addr);
        }

        if ($bodyHtml !== '') {
            $email->html($bodyHtml);
            $email->text($bodyText !== '' ? $bodyText : strip_tags($bodyHtml));
        } else {
            $email->text($bodyText);
        }

        foreach ($attachments as $file) {
            if ($file instanceof UploadedFile && $file->isValid()) {
                $email->attach(
                    (string) file_get_contents($file->getRealPath()),
                    $file->getClientOriginalName(),
                    $file->getMimeType() ?? 'application/octet-stream',
                );
            }
        }

        (new SymfonyMailer($transport))->send($email);

        return $email->toString();
    }

    // ------------------------------------------------------------------

    private function buildTransport(string $username, string $password): EsmtpTransport
    {
        $host = config('smtp.host', '127.0.0.1');
        $port = (int) config('smtp.port', 587);
        $enc  = strtolower((string) config('smtp.encryption', ''));

        // tls=true  → SMTPS (port 465, TLS from the start)
        // tls=false → plain connection; STARTTLS is negotiated if the server offers it
        $tls = ($enc === 'ssl');

        $transport = new EsmtpTransport($host, $port, $tls);

        // Disable peer verification for self-signed / local certs
        if (!config('smtp.validate_cert', false)) {
            $transport->getStream()->setStreamOptions([
                'ssl' => [
                    'verify_peer'       => false,
                    'verify_peer_name'  => false,
                    'allow_self_signed' => true,
                ],
            ]);
        }

        if ($username !== '') {
            $transport->setUsername($username);
            $transport->setPassword($password);
        }

        return $transport;
    }

    /**
     * Parse a comma/semicolon-separated address string into Symfony Address objects.
     *
     * @return Address[]
     */
    private function parseAddresses(string $raw): array
    {
        if (trim($raw) === '') {
            return [];
        }

        $addresses = [];
        foreach (preg_split('/[,;]/', $raw) ?: [] as $part) {
            $part = trim($part);
            if ($part === '') {
                continue;
            }
            // "Display Name" <email>  or  Display Name <email>
            if (preg_match('/^"?(.+?)"?\s*<([^>]+)>$/', $part, $m)) {
                $addresses[] = new Address(trim($m[2]), trim($m[1], ' "'));
            } else {
                $addresses[] = new Address($part);
            }
        }

        return $addresses;
    }
}
