<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Services;

/**
 * Pure-PHP TOTP (RFC 6238) implementation.
 * No external dependencies — uses PHP's hash_hmac + random_bytes.
 */
class TotpService
{
    private const BASE32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    private const PERIOD  = 30;
    private const DIGITS  = 6;

    // ------------------------------------------------------------------

    public function generateSecret(): string
    {
        return $this->base32Encode(random_bytes(20));
    }

    /**
     * Build an otpauth:// URI suitable for QR-code display.
     */
    public function getQrUri(string $email, string $secret): string
    {
        $issuer = config('app.name', 'Opterius Mail');
        $label  = rawurlencode($issuer . ':' . $email);
        return sprintf(
            'otpauth://totp/%s?secret=%s&issuer=%s&algorithm=SHA1&digits=%d&period=%d',
            $label,
            $secret,
            rawurlencode($issuer),
            self::DIGITS,
            self::PERIOD,
        );
    }

    /**
     * Verify a 6-digit TOTP code.
     * Allows ±1 time window to account for clock skew.
     */
    public function verify(string $secret, string $code): bool
    {
        $code = str_pad(preg_replace('/\D/', '', $code), self::DIGITS, '0', STR_PAD_LEFT);
        $key  = $this->base32Decode($secret);
        $ts   = (int) floor(time() / self::PERIOD);

        for ($i = -1; $i <= 1; $i++) {
            if ($this->hotp($key, $ts + $i) === $code) {
                return true;
            }
        }

        return false;
    }

    /**
     * Generate 10 one-time recovery codes (each is a 10-character hex string).
     *
     * @return string[]
     */
    public function generateRecoveryCodes(): array
    {
        $codes = [];
        for ($i = 0; $i < 10; $i++) {
            $codes[] = strtoupper(implode('-', str_split(bin2hex(random_bytes(5)), 5)));
        }
        return $codes;
    }

    // ------------------------------------------------------------------

    private function hotp(string $key, int $counter): string
    {
        $data = pack('J', $counter);                        // 8-byte big-endian
        $hash = hash_hmac('sha1', $data, $key, true);      // 20-byte SHA-1 HMAC
        $off  = ord($hash[19]) & 0x0f;
        $code = (
            ((ord($hash[$off])     & 0x7f) << 24) |
            ((ord($hash[$off + 1]) & 0xff) << 16) |
            ((ord($hash[$off + 2]) & 0xff) << 8)  |
             (ord($hash[$off + 3]) & 0xff)
        ) % (10 ** self::DIGITS);

        return str_pad((string) $code, self::DIGITS, '0', STR_PAD_LEFT);
    }

    private function base32Encode(string $bytes): string
    {
        $alphabet = self::BASE32;
        $result   = '';
        $n        = strlen($bytes);

        for ($i = 0; $i < $n; $i += 5) {
            $chunk = str_pad(substr($bytes, $i, 5), 5, "\0");
            $b     = array_map('ord', str_split($chunk));
            $result .= $alphabet[($b[0] >> 3) & 0x1f];
            $result .= $alphabet[(($b[0] << 2) | ($b[1] >> 6)) & 0x1f];
            $result .= $alphabet[($b[1] >> 1) & 0x1f];
            $result .= $alphabet[(($b[1] << 4) | ($b[2] >> 4)) & 0x1f];
            $result .= $alphabet[(($b[2] << 1) | ($b[3] >> 7)) & 0x1f];
            $result .= $alphabet[($b[3] >> 2) & 0x1f];
            $result .= $alphabet[(($b[3] << 3) | ($b[4] >> 5)) & 0x1f];
            $result .= $alphabet[$b[4] & 0x1f];
        }

        $pad = [0, 6, 4, 3, 1][$n % 5];
        return $pad ? substr($result, 0, -$pad) : $result;
    }

    private function base32Decode(string $data): string
    {
        $data     = strtoupper(rtrim($data, '='));
        $alphabet = self::BASE32;
        $buf      = 0;
        $bits     = 0;
        $result   = '';

        for ($i = 0, $len = strlen($data); $i < $len; $i++) {
            $val = strpos($alphabet, $data[$i]);
            if ($val === false) {
                continue;
            }
            $buf  = ($buf << 5) | $val;
            $bits += 5;
            if ($bits >= 8) {
                $bits   -= 8;
                $result .= chr(($buf >> $bits) & 0xff);
            }
        }

        return $result;
    }
}
