<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Api;

use App\Auth\ImapGuard;
use App\Http\Controllers\Controller;
use App\Services\ImapConnection;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CheckNewMailController extends Controller
{
    /**
     * GET /api/check-new
     *
     * Runs IMAP STATUS on INBOX and returns unseen count + whether genuinely
     * new messages arrived since the last check (UIDNEXT increased).
     * Called by the browser every 45 seconds.
     */
    public function __invoke(Request $request): JsonResponse
    {
        /** @var ImapGuard $guard */
        $guard = auth('web');

        $imap = new ImapConnection();

        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      8,
            );

            $imap->login($guard->getImapLogin(), $guard->getImapPassword());

            $status = $imap->getFolderStatus('INBOX');

        } catch (\Throwable) {
            return response()->json(['error' => 'imap_unavailable'], 503);
        }

        // Detect genuinely new messages: UIDNEXT increased since last check.
        $lastUidnext = session('check_new_uidnext');
        $hasNew      = $lastUidnext !== null && $status['uidnext'] > $lastUidnext;

        session(['check_new_uidnext' => $status['uidnext']]);

        return response()->json([
            'unseen'  => $status['unseen'],
            'has_new' => $hasNew,
        ]);
    }
}
