<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Api;

use App\Auth\ImapGuard;
use App\Http\Controllers\Controller;
use App\Services\ImapConnection;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class MessagesController extends Controller
{
    private const MAX_PER_PAGE = 100;

    /**
     * GET /api/messages
     *
     * Returns a paginated list of message summaries from a mailbox folder.
     *
     * Query params:
     *   folder   — mailbox name (default: INBOX)
     *   page     — 1-based page number (default: 1)
     *   per_page — messages per page, max 100 (default: 25)
     *
     * Response:
     *   folder, page, per_page, total, messages[]
     *     message: uid, from_name, from_email, subject, date, flags{seen,flagged,answered}
     */
    public function index(Request $request): JsonResponse
    {
        $folder  = $request->input('folder', 'INBOX');
        $page    = max(1, (int) $request->input('page', 1));
        $perPage = min(self::MAX_PER_PAGE, max(1, (int) $request->input('per_page', 25)));

        /** @var ImapGuard $guard */
        $guard = auth('web');

        $imap = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());

            $status = $imap->getFolderStatus($folder);
            $total  = $status['exists'] ?? 0;

            $messages = [];

            if ($total > 0) {
                $imap->selectFolder($folder);

                // Calculate sequence range (newest-first, 1-based message sequence numbers)
                $lastSeq  = $total - ($page - 1) * $perPage;
                $firstSeq = max(1, $lastSeq - $perPage + 1);

                if ($lastSeq >= 1) {
                    $range = "{$firstSeq}:{$lastSeq}";
                    $uids  = $imap->search("ALL {$range}") ?: [];

                    if (!empty($uids)) {
                        $uids     = array_reverse($uids);
                        $headers  = $imap->fetchHeadersByUids($uids);
                        $messages = array_values(array_map(
                            fn($h) => $this->formatMessage($h),
                            $headers,
                        ));
                    }
                }
            }

            $imap->logout();

        } catch (\Throwable $e) {
            $imap->close();
            return response()->json(['error' => $e->getMessage()], 503);
        }

        return response()->json([
            'folder'   => $folder,
            'page'     => $page,
            'per_page' => $perPage,
            'total'    => $total,
            'messages' => $messages,
        ]);
    }

    private function formatMessage(array $h): array
    {
        $flags = array_map('strtolower', $h['flags'] ?? []);

        return [
            'uid'        => $h['uid'],
            'from_name'  => $h['from']['name']  ?? '',
            'from_email' => $h['from']['email'] ?? '',
            'subject'    => $h['subject'] ?? '(no subject)',
            'date'       => $h['date']    ?? '',
            'seen'       => in_array('\\seen',     $flags, true),
            'flagged'    => in_array('\\flagged',  $flags, true),
            'answered'   => in_array('\\answered', $flags, true),
        ];
    }
}
