<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

use App\Http\Controllers\Admin\AccountController;
use App\Http\Controllers\Admin\AliasController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\AutoresponderController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DkimController;
use App\Http\Controllers\Admin\DomainController;
use App\Http\Controllers\Admin\GroupController;
use App\Http\Controllers\Admin\LogController;
use App\Http\Controllers\Admin\QueueController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\SpamController;
use Illuminate\Support\Facades\Route;

// ------------------------------------------------------------------
// Admin guest routes (login, setup, 2FA)
// ------------------------------------------------------------------

Route::prefix('admin')->name('admin.')->group(function () {

    // First-run setup (only works when no admins exist)
    Route::get('/setup', [AuthController::class, 'showSetup'])->name('setup');
    Route::post('/setup', [AuthController::class, 'setup'])->name('setup.submit');

    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.submit')
         ->middleware('throttle:5,1');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/2fa', [AuthController::class, 'show2fa'])->name('2fa');
    Route::post('/2fa', [AuthController::class, 'verify2fa'])->name('2fa.verify');

    // ------------------------------------------------------------------
    // Authenticated admin routes
    // ------------------------------------------------------------------

    Route::middleware('admin.auth')->group(function () {

        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

        // Mail groups (always available, both modes)
        Route::get('/groups', [GroupController::class, 'index'])->name('groups.index');
        Route::post('/groups', [GroupController::class, 'store'])->name('groups.store');
        Route::put('/groups/{mail_group}', [GroupController::class, 'update'])->name('groups.update');
        Route::delete('/groups/{mail_group}', [GroupController::class, 'destroy'])->name('groups.destroy');

        // Domains
        Route::get('/domains', [DomainController::class, 'index'])->name('domains.index');
        Route::post('/domains', [DomainController::class, 'store'])->name('domains.store');
        Route::delete('/domains/{domain}', [DomainController::class, 'destroy'])->name('domains.destroy');
        Route::get('/domains/{domain}/dns', [DomainController::class, 'dns'])->name('domains.dns');

        // Accounts
        Route::get('/accounts', [AccountController::class, 'index'])->name('accounts.index');
        Route::get('/accounts/create', [AccountController::class, 'create'])->name('accounts.create');
        Route::post('/accounts', [AccountController::class, 'store'])->name('accounts.store');
        Route::get('/accounts/{account}/edit', [AccountController::class, 'edit'])->name('accounts.edit');
        Route::put('/accounts/{account}', [AccountController::class, 'update'])->name('accounts.update');
        Route::delete('/accounts/{account}', [AccountController::class, 'destroy'])->name('accounts.destroy');
        Route::post('/accounts/{account}/disable-2fa', [AccountController::class, 'disable2fa'])->name('accounts.disable2fa');

        // Aliases
        Route::get('/aliases', [AliasController::class, 'index'])->name('aliases.index');
        Route::post('/aliases', [AliasController::class, 'store'])->name('aliases.store');
        Route::delete('/aliases/{alias}', [AliasController::class, 'destroy'])->name('aliases.destroy');

        // Autoresponders
        Route::get('/autoresponders', [AutoresponderController::class, 'index'])->name('autoresponders.index');
        Route::post('/autoresponders', [AutoresponderController::class, 'store'])->name('autoresponders.store');
        Route::delete('/autoresponders/{autoresponder}', [AutoresponderController::class, 'destroy'])->name('autoresponders.destroy');

        // Spam
        Route::get('/spam', [SpamController::class, 'index'])->name('spam.index');
        Route::post('/spam', [SpamController::class, 'update'])->name('spam.update');

        // DKIM
        Route::get('/dkim', [DkimController::class, 'index'])->name('dkim.index');
        Route::post('/dkim/{domain}', [DkimController::class, 'generate'])->name('dkim.generate');

        // Mail queue
        Route::get('/queue', [QueueController::class, 'index'])->name('queue.index');
        Route::post('/queue/flush', [QueueController::class, 'flush'])->name('queue.flush');
        Route::delete('/queue/{id}', [QueueController::class, 'destroy'])->name('queue.destroy');

        // Logs
        Route::get('/logs', [LogController::class, 'index'])->name('logs.index');

        // Settings
        Route::get('/settings', [SettingController::class, 'index'])->name('settings.index');
        Route::post('/settings', [SettingController::class, 'update'])->name('settings.update');
    });
});
