<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

use App\Http\Controllers\AttachmentController;
use App\Http\Controllers\BulkMessageController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ComposeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FolderController;
use App\Http\Controllers\InboxController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SieveController;
use App\Http\Controllers\SpamController;
use App\Http\Controllers\TwoFactorController;
use App\Http\Controllers\ReadReceiptController;
use App\Http\Controllers\Api\CheckNewMailController;
use App\Http\Controllers\Api\MessagesController;
use App\Http\Controllers\Api\SyncController;
use App\Http\Controllers\ContactGroupController;
use App\Http\Controllers\SsoController;
use App\Http\Controllers\ScreenerController;
use App\Http\Controllers\SnoozeController;
use App\Http\Controllers\SetAsideController;
use App\Http\Controllers\ReplyLaterController;
use App\Http\Controllers\EmailNoteController;
use App\Http\Controllers\ScheduledEmailController;
use App\Http\Controllers\FeedController;
use Illuminate\Support\Facades\Route;

// ------------------------------------------------------------------
// Internal agent sync (server-to-server, no CSRF)
// ------------------------------------------------------------------

Route::post('/api/sync/account', [SyncController::class, 'account']);

// ------------------------------------------------------------------
// Panel SSO routes
// ------------------------------------------------------------------

// Issue endpoint: called server-to-server from the panel (no CSRF).
Route::post('/sso/issue', [SsoController::class, 'issue'])
    ->withoutMiddleware(\Illuminate\Foundation\Http\Middleware\ValidateCsrfToken::class);

// Login endpoint: user browser arrives here with a one-time token.
Route::get('/sso/login', [SsoController::class, 'login'])->name('sso.login');

// ------------------------------------------------------------------
// Guest routes
// ------------------------------------------------------------------

Route::middleware('guest:web')->group(function () {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.submit')
         ->middleware('throttle:5,1');
});

Route::get('/2fa', [AuthController::class, 'show2fa'])->name('2fa');
Route::post('/2fa', [AuthController::class, 'verify2fa'])->name('2fa.verify');

Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

// ------------------------------------------------------------------
// Authenticated webmail routes
// ------------------------------------------------------------------

Route::middleware('imap.auth')->group(function () {

    // Inbox / folder view
    Route::get('/', [InboxController::class, 'index'])->name('inbox');
    Route::get('/folder/{folder}', [InboxController::class, 'folder'])->name('folder');

    // Message actions
    Route::get('/message/{folder}/{uid}', [MessageController::class, 'show'])->name('message.show');
    Route::delete('/message/{folder}/{uid}', [MessageController::class, 'destroy'])->name('message.destroy');
    Route::post('/message/{folder}/{uid}/move', [MessageController::class, 'move'])->name('message.move');
    Route::post('/message/{folder}/{uid}/flag', [MessageController::class, 'flag'])->name('message.flag');
    Route::post('/message/{folder}/{uid}/spam',    [SpamController::class, 'markSpam'])->name('message.spam');
    Route::post('/message/{folder}/{uid}/notspam', [SpamController::class, 'markNotSpam'])->name('message.notspam');
    Route::get('/message/{folder}/{uid}/print',   [MessageController::class, 'print'])->name('message.print');
    Route::post('/message/{folder}/{uid}/receipt', [ReadReceiptController::class, 'send'])->name('message.receipt');

    // Compose
    Route::get('/compose', [ComposeController::class, 'create'])->name('compose');
    Route::get('/reply/{folder}/{uid}', [ComposeController::class, 'reply'])->name('compose.reply');
    Route::get('/forward/{folder}/{uid}', [ComposeController::class, 'forward'])->name('compose.forward');
    Route::post('/send', [ComposeController::class, 'send'])->name('compose.send');
    Route::post('/draft', [ComposeController::class, 'saveDraft'])->name('compose.draft');

    // Search
    Route::get('/search', [SearchController::class, 'index'])->name('search');

    // Contacts
    Route::get('/contacts', [ContactController::class, 'index'])->name('contacts');
    Route::post('/contacts', [ContactController::class, 'store'])->name('contacts.store');
    Route::get('/contacts/search', [ContactController::class, 'autocomplete'])->name('contacts.autocomplete');
    Route::get('/contacts/export', [ContactController::class, 'export'])->name('contacts.export');
    Route::post('/contacts/import', [ContactController::class, 'import'])->name('contacts.import');
    Route::get('/contacts/{contact}', [ContactController::class, 'show'])->name('contacts.show');
    Route::put('/contacts/{contact}', [ContactController::class, 'update'])->name('contacts.update');
    Route::delete('/contacts/{contact}', [ContactController::class, 'destroy'])->name('contacts.destroy');

    // Contact groups
    Route::post('/contact-groups', [ContactGroupController::class, 'store'])->name('contact-groups.store');
    Route::put('/contact-groups/{contactGroup}', [ContactGroupController::class, 'update'])->name('contact-groups.update');
    Route::delete('/contact-groups/{contactGroup}', [ContactGroupController::class, 'destroy'])->name('contact-groups.destroy');

    // Settings
    Route::get('/settings', [SettingController::class, 'index'])->name('settings');
    Route::post('/settings', [SettingController::class, 'update'])->name('settings.update');

    // Two-factor authentication setup
    Route::get('/settings/2fa',          [TwoFactorController::class, 'show'])->name('2fa.setup');
    Route::post('/settings/2fa/enable',  [TwoFactorController::class, 'enable'])->name('2fa.enable');
    Route::post('/settings/2fa/disable', [TwoFactorController::class, 'disable'])->name('2fa.disable');

    // Sieve filtering rules
    Route::get('/sieve',         [SieveController::class, 'index'])->name('sieve.index');
    Route::post('/sieve',        [SieveController::class, 'store'])->name('sieve.store');
    Route::delete('/sieve/{id}', [SieveController::class, 'destroy'])->name('sieve.destroy');

    // Attachments
    Route::get('/attachment/{folder}/{uid}/{part}', [AttachmentController::class, 'download'])->name('attachment.download');

    // Folder management (names in request body — not route segments — to allow slashes in names)
    Route::post('/folders',   [FolderController::class, 'store'])->name('folders.store');
    Route::put('/folders',    [FolderController::class, 'update'])->name('folders.update');
    Route::delete('/folders', [FolderController::class, 'destroy'])->name('folders.destroy');

    // Bulk message actions (delete, read, unread, flag, move)
    Route::post('/bulk', BulkMessageController::class)->name('messages.bulk');

    // Real-time new mail polling (browser calls every 45 s)
    Route::get('/api/check-new', CheckNewMailController::class)->name('api.check-new');

    // Paginated message list API
    Route::get('/api/messages', [MessagesController::class, 'index'])->name('api.messages');

    // Screener
    Route::get('/screener', [ScreenerController::class, 'index'])->name('screener.index');
    Route::post('/screener/approve', [ScreenerController::class, 'approve'])->name('screener.approve');
    Route::post('/screener/block', [ScreenerController::class, 'block'])->name('screener.block');
    Route::delete('/screener', [ScreenerController::class, 'destroy'])->name('screener.destroy');

    // Snooze
    Route::get('/snoozed', [SnoozeController::class, 'index'])->name('snooze.index');
    Route::post('/snooze', [SnoozeController::class, 'store'])->name('snooze.store');
    Route::delete('/snooze', [SnoozeController::class, 'destroy'])->name('snooze.destroy');

    // Set Aside
    Route::get('/set-aside', [SetAsideController::class, 'index'])->name('set-aside.index');
    Route::post('/set-aside', [SetAsideController::class, 'store'])->name('set-aside.store');
    Route::delete('/set-aside', [SetAsideController::class, 'destroy'])->name('set-aside.destroy');

    // Reply Later
    Route::get('/reply-later', [ReplyLaterController::class, 'index'])->name('reply-later.index');
    Route::post('/reply-later', [ReplyLaterController::class, 'store'])->name('reply-later.store');
    Route::delete('/reply-later', [ReplyLaterController::class, 'destroy'])->name('reply-later.destroy');

    // Email Notes
    Route::post('/note', [EmailNoteController::class, 'store'])->name('note.store');
    Route::delete('/note', [EmailNoteController::class, 'destroy'])->name('note.destroy');

    // Scheduled Emails
    Route::get('/scheduled', [ScheduledEmailController::class, 'index'])->name('scheduled.index');
    Route::post('/scheduled', [ScheduledEmailController::class, 'store'])->name('scheduled.store');
    Route::delete('/scheduled/{scheduledEmail}', [ScheduledEmailController::class, 'destroy'])->name('scheduled.destroy');

    // Feed
    Route::get('/feed', [FeedController::class, 'index'])->name('feed.index');
    Route::post('/feed', [FeedController::class, 'store'])->name('feed.store');
    Route::delete('/feed', [FeedController::class, 'destroy'])->name('feed.destroy');
});
