<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

use App\Http\Controllers\AttachmentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ComposeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\InboxController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingController;
use Illuminate\Support\Facades\Route;

// ------------------------------------------------------------------
// Guest routes
// ------------------------------------------------------------------

Route::middleware('guest:web')->group(function () {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.submit')
         ->middleware('throttle:5,1');
});

Route::get('/2fa', [AuthController::class, 'show2fa'])->name('2fa');
Route::post('/2fa', [AuthController::class, 'verify2fa'])->name('2fa.verify');

Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

// ------------------------------------------------------------------
// Authenticated webmail routes
// ------------------------------------------------------------------

Route::middleware('imap.auth')->group(function () {

    // Inbox / folder view
    Route::get('/', [InboxController::class, 'index'])->name('inbox');
    Route::get('/folder/{folder}', [InboxController::class, 'folder'])->name('folder');

    // Message actions
    Route::get('/message/{folder}/{uid}', [MessageController::class, 'show'])->name('message.show');
    Route::delete('/message/{folder}/{uid}', [MessageController::class, 'destroy'])->name('message.destroy');
    Route::post('/message/{folder}/{uid}/move', [MessageController::class, 'move'])->name('message.move');
    Route::post('/message/{folder}/{uid}/flag', [MessageController::class, 'flag'])->name('message.flag');

    // Compose
    Route::get('/compose', [ComposeController::class, 'create'])->name('compose');
    Route::get('/reply/{folder}/{uid}', [ComposeController::class, 'reply'])->name('compose.reply');
    Route::get('/forward/{folder}/{uid}', [ComposeController::class, 'forward'])->name('compose.forward');
    Route::post('/send', [ComposeController::class, 'send'])->name('compose.send');
    Route::post('/draft', [ComposeController::class, 'saveDraft'])->name('compose.draft');

    // Search
    Route::get('/search', [SearchController::class, 'index'])->name('search');

    // Contacts
    Route::get('/contacts', [ContactController::class, 'index'])->name('contacts');
    Route::post('/contacts', [ContactController::class, 'store'])->name('contacts.store');
    Route::get('/contacts/search', [ContactController::class, 'autocomplete'])->name('contacts.autocomplete');
    Route::get('/contacts/{contact}', [ContactController::class, 'show'])->name('contacts.show');
    Route::put('/contacts/{contact}', [ContactController::class, 'update'])->name('contacts.update');
    Route::delete('/contacts/{contact}', [ContactController::class, 'destroy'])->name('contacts.destroy');

    // Settings
    Route::get('/settings', [SettingController::class, 'index'])->name('settings');
    Route::post('/settings', [SettingController::class, 'update'])->name('settings.update');

    // Attachments
    Route::get('/attachment/{folder}/{uid}/{part}', [AttachmentController::class, 'download'])->name('attachment.download');
});
