<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel / Opterius
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Chimilevschi Iosif-Gabriel / Opterius
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Chimilevschi Iosif-Gabriel <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Auth;

use Illuminate\Contracts\Auth\Authenticatable;

/**
 * Represents a logged-in webmail user.
 * There is no local DB record — identity comes from the IMAP session.
 */
class ImapUser implements Authenticatable
{
    public function __construct(
        public readonly string $email,
        public readonly string $name = '',
    ) {}

    // ------------------------------------------------------------------
    // Authenticatable contract
    // ------------------------------------------------------------------

    public function getAuthIdentifierName(): string
    {
        return 'email';
    }

    public function getAuthIdentifier(): string
    {
        return $this->email;
    }

    public function getAuthPasswordName(): string
    {
        return 'password';
    }

    public function getAuthPassword(): string
    {
        // Password is never stored in the model — kept encrypted in the session.
        return '';
    }

    public function getRememberToken(): string
    {
        return '';
    }

    public function setRememberToken(#[\SensitiveParameter] $value): void
    {
        // Remember-me is handled via encrypted cookie, not a DB token.
    }

    public function getRememberTokenName(): string
    {
        return '';
    }
}
