<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel / Opterius
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Chimilevschi Iosif-Gabriel / Opterius
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Chimilevschi Iosif-Gabriel <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Auth;

use App\Services\ImapConnection;
use Illuminate\Auth\GuardHelpers;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Http\Request;

/**
 * Custom auth guard that authenticates users against an IMAP server.
 * No local user table — credentials are stored encrypted in the session.
 */
class ImapGuard implements Guard
{
    use GuardHelpers;

    public function __construct(protected Request $request) {}

    // ------------------------------------------------------------------
    // Guard contract
    // ------------------------------------------------------------------

    public function user(): ?ImapUser
    {
        if ($this->user !== null) {
            return $this->user;
        }

        if (!session()->has('imap_email')) {
            return null;
        }

        return $this->user = new ImapUser(
            email: session('imap_email'),
            name: session('imap_display_name', ''),
        );
    }

    public function validate(array $credentials = []): bool
    {
        return $this->testCredentials($credentials['email'] ?? '', $credentials['password'] ?? '');
    }

    // ------------------------------------------------------------------
    // Stateful helpers used by controllers
    // ------------------------------------------------------------------

    /**
     * Attempt to authenticate and create a session on success.
     */
    public function attempt(array $credentials): bool
    {
        $email    = $credentials['email'] ?? '';
        $password = $credentials['password'] ?? '';

        if (!$this->testCredentials($email, $password)) {
            return false;
        }

        session([
            'imap_email'        => $email,
            'imap_password'     => encrypt($password),
            'imap_display_name' => $credentials['name'] ?? $email,
        ]);

        $this->user = new ImapUser(email: $email, name: $credentials['name'] ?? $email);

        return true;
    }

    public function logout(): void
    {
        session()->forget(['imap_email', 'imap_password', 'imap_display_name', '2fa_pending']);
        session()->invalidate();
        session()->regenerateToken();
        $this->user = null;
    }

    /**
     * Retrieve the stored IMAP password from the session (decrypted).
     * Used by ImapService to reconnect for each request.
     */
    public function getImapPassword(): ?string
    {
        $encrypted = session('imap_password');
        if (!$encrypted) {
            return null;
        }
        try {
            return decrypt($encrypted);
        } catch (\Throwable) {
            return null;
        }
    }

    // ------------------------------------------------------------------
    // Internal
    // ------------------------------------------------------------------

    private function testCredentials(string $email, string $password): bool
    {
        if ($email === '' || $password === '') {
            return false;
        }

        $conn = new ImapConnection();
        try {
            $conn->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $ok = $conn->login($email, $password);
            $conn->logout();
            return $ok;
        } catch (\Throwable) {
            return false;
        }
    }
}
