<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('autoresponders', function (Blueprint $table) {
            $table->id();
            $table->string('email', 255)->index();
            $table->string('subject', 255)->default('');
            $table->text('body');
            $table->date('starts_at')->nullable();
            $table->date('ends_at')->nullable();
            $table->boolean('is_active')->default(true)->index();
            $table->timestamps();
        });

        // Track which senders have already received an autoresponse to prevent loops
        Schema::create('autoresponder_log', function (Blueprint $table) {
            $table->id();
            $table->foreignId('autoresponder_id')->constrained('autoresponders')->cascadeOnDelete();
            $table->string('to_email', 255);
            $table->timestamp('created_at')->useCurrent()->index();
            $table->unique(['autoresponder_id', 'to_email']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('autoresponder_log');
        Schema::dropIfExists('autoresponders');
    }
};
