<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

return [
    'template'   => env('MAIL_UI_TEMPLATE', 'default'),
    'admin_mode' => env('MAIL_ADMIN', false),

    // Admin URL prefix. Change to something hard-to-guess for extra security.
    // Example: MAIL_ADMIN_PREFIX=x9k2-panel → accessible at /x9k2-panel/login
    'admin_prefix' => env('MAIL_ADMIN_PREFIX', 'admin'),

    // IP allowlist for the admin area. Comma-separated. Empty = no restriction.
    // Example: MAIL_ADMIN_IPS=1.2.3.4,5.6.7.8
    'admin_allowed_ips' => array_filter(array_map('trim', explode(',', env('MAIL_ADMIN_IPS', '')))),

    // Panel SSO — token-based auto-login from Opterius Panel (or any trusted host).
    // Set PANEL_SSO_SECRET to the same value on the panel side.
    'sso_enabled' => env('PANEL_SSO_ENABLED', false),
    'sso_secret'  => env('PANEL_SSO_SECRET'),

    // Agent account sync — shared secret for the /api/sync/account endpoint.
    // Set this to match mail_sync_secret in the agent config.
    // Leave blank to disable the sync endpoint (standalone mode).
    'sync_secret' => env('MAIL_SYNC_SECRET'),
];
