<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

return [
    /*
     * Enable the /admin area and mail server management features.
     * When false, Opterius Mail is a webmail-only client (like Roundcube).
     */
    'enabled' => env('MAIL_ADMIN', false),

    /*
     * Mail server backend for account management.
     * Supported: "passwd-file", "mysql"
     */
    'backend' => env('MAIL_BACKEND', 'passwd-file'),

    /*
     * passwd-file backend paths (Dovecot)
     */
    'passwd_file'   => env('DOVECOT_PASSWD_FILE', '/etc/dovecot/users'),
    'maildir_base'  => env('MAILDIR_BASE', '/var/mail/vdomains'),
    'postfix_vmailbox' => env('POSTFIX_VMAILBOX', '/etc/postfix/vmailbox'),
    'postfix_virtual'  => env('POSTFIX_VIRTUAL', '/etc/postfix/virtual'),

    /*
     * Require all webmail users to have 2FA enabled.
     */
    'require_2fa' => env('MAIL_REQUIRE_2FA', false),

    /*
     * SSO shared secret (for Opterius Panel integration).
     */
    'sso_secret' => env('MAIL_SSO_SECRET', null),
    'sso_ttl'    => (int) env('MAIL_SSO_TTL', 30),
];
