<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

if (!function_exists('mailView')) {
    /**
     * Resolve a view path within the active mail UI template.
     *
     * If the active template does not provide the requested view,
     * the function falls back to the built-in 'default' template
     * automatically. This lets a custom template override only the
     * views it needs without re-implementing everything.
     *
     * Usage: return view(mailView('inbox.index'), $data);
     */
    function mailView(string $view): string
    {
        $template = config('mail-ui.template', 'default');

        if ($template !== 'default') {
            $custom = "templates.{$template}.{$view}";
            if (view()->exists($custom)) {
                return $custom;
            }
        }

        return "templates.default.{$view}";
    }
}

if (!function_exists('userSettings')) {
    /**
     * Return the UserSetting row for the currently authenticated webmail user.
     * Creates the row with defaults on first access. Cached for the lifetime of the request.
     */
    function userSettings(): \App\Models\UserSetting
    {
        static $cache = null;
        if ($cache !== null) {
            return $cache;
        }

        $email = auth('web')->user()?->email;

        if (!$email) {
            return new \App\Models\UserSetting(\App\Models\UserSetting::defaults());
        }

        return $cache = \App\Models\UserSetting::firstOrCreate(
            ['email' => $email],
            \App\Models\UserSetting::defaults(),
        );
    }
}
