<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapGuard;
use App\Services\ImapConnection;
use App\Services\MimeParser;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;

class AttachmentController extends Controller
{
    public function download(Request $request, string $folder, string $uid, string $part): mixed
    {
        $partIndex = (int) $part;
        if ($partIndex < 0) {
            abort(400);
        }

        /** @var ImapGuard $guard */
        $guard = auth('web');
        $imap  = new ImapConnection();

        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $imap->selectFolder($folder);
            $fetched = $imap->fetchMessageRaw((int) $uid);
            $imap->logout();
        } catch (\Throwable) {
            $imap->close();
            abort(503, 'Could not connect to mail server.');
        }

        if ($fetched['raw'] === '') {
            abort(404);
        }

        $attachment = (new MimeParser())->extractPart($fetched['raw'], $partIndex);

        if ($attachment === null) {
            abort(404, 'Attachment not found.');
        }

        $filename = $attachment['name'] !== '' ? $attachment['name'] : 'attachment';
        $mimeType = $attachment['type'] !== '' ? $attachment['type'] : 'application/octet-stream';
        $data     = $attachment['data'];

        return response()->streamDownload(
            function () use ($data) { echo $data; },
            $filename,
            [
                'Content-Type'   => $mimeType,
                'Content-Length' => strlen($data),
            ],
        );
    }
}
