<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Models\LoginLog;
use App\Models\UserTwoFactor;
use App\Services\TotpService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    public function showLogin()
    {
        return view(mailView('auth.login'));
    }

    public function login(Request $request)
    {
        $credentials = $request->validate([
            'email'    => ['required', 'email'],
            'password' => ['required'],
        ]);

        /** @var \App\Auth\ImapGuard $guard */
        $guard = Auth::guard('web');

        if (!$guard->attempt($credentials)) {
            LoginLog::record($credentials['email'], $request, false);

            return back()
                ->withInput($request->only('email'))
                ->withErrors(['email' => 'Invalid email or password.']);
        }

        LoginLog::record($credentials['email'], $request, true);

        $request->session()->regenerate();

        // Check if 2FA is enabled for this account
        $tf = UserTwoFactor::where('email', $credentials['email'])
            ->whereNotNull('enabled_at')
            ->first();

        if ($tf) {
            session(['2fa_pending' => true]);
            return redirect()->route('2fa');
        }

        return redirect()->intended(route('inbox'));
    }

    public function logout(Request $request)
    {
        Auth::guard('web')->logout();
        return redirect()->route('login');
    }

    public function show2fa()
    {
        if (!session('2fa_pending')) {
            return redirect()->route('inbox');
        }
        return view(mailView('auth.2fa'));
    }

    public function verify2fa(Request $request)
    {
        if (!session('2fa_pending')) {
            return redirect()->route('inbox');
        }

        $request->validate(['code' => ['required', 'string']]);

        $email  = session('imap_email');
        $record = UserTwoFactor::where('email', $email)->whereNotNull('enabled_at')->first();

        if (!$record) {
            session()->forget('2fa_pending');
            return redirect()->route('inbox');
        }

        $secret = decrypt($record->secret);
        $totp   = new TotpService();

        $valid = $totp->verify($secret, $request->input('code'))
            || $this->consumeRecoveryCode($record, $request->input('code'));

        if (!$valid) {
            return back()->withErrors(['code' => 'Invalid code. Check your authenticator app or use a recovery code.']);
        }

        session()->forget('2fa_pending');

        return redirect()->intended(route('inbox'));
    }

    // ------------------------------------------------------------------

    private function consumeRecoveryCode(UserTwoFactor $record, string $code): bool
    {
        $codes = $record->getRecoveryCodesArray();
        $clean = strtoupper(str_replace(['-', ' '], '', $code));

        foreach ($codes as $i => $stored) {
            if (strtoupper(str_replace('-', '', $stored)) === $clean) {
                unset($codes[$i]);
                $record->update(['recovery_codes' => json_encode(array_values($codes))]);
                return true;
            }
        }

        return false;
    }
}
