<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel / Opterius
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Chimilevschi Iosif-Gabriel / Opterius
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Chimilevschi Iosif-Gabriel <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    public function showLogin()
    {
        return view(mailView('auth.login'));
    }

    public function login(Request $request)
    {
        $credentials = $request->validate([
            'email'    => ['required', 'email'],
            'password' => ['required'],
        ]);

        /** @var \App\Auth\ImapGuard $guard */
        $guard = Auth::guard('web');

        if (!$guard->attempt($credentials)) {
            return back()
                ->withInput($request->only('email'))
                ->withErrors(['email' => 'Invalid email or password.']);
        }

        $request->session()->regenerate();

        return redirect()->intended(route('inbox'));
    }

    public function logout(Request $request)
    {
        Auth::guard('web')->logout();
        return redirect()->route('login');
    }

    public function show2fa()
    {
        if (!session('2fa_pending')) {
            return redirect()->route('inbox');
        }
        return view(mailView('auth.2fa'));
    }

    public function verify2fa(Request $request)
    {
        // 2FA verification will be implemented when the 2FA feature is built.
        return redirect()->route('inbox');
    }
}
