<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapGuard;
use App\Models\AdminSetting;
use App\Models\MailGroup;
use App\Models\MailSendLog;
use App\Services\ImapConnection;
use App\Services\MimeParser;
use App\Services\SmtpSender;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email;

class ComposeController extends Controller
{
    // ------------------------------------------------------------------
    // Display
    // ------------------------------------------------------------------

    public function create(Request $request): mixed
    {
        $draftUid    = (int) $request->query('draft_uid', 0);
        $draftFolder = (string) $request->query('draft_folder', '');

        // Pre-fill from an existing draft when ?draft_uid= is present.
        if ($draftUid > 0 && $draftFolder !== '') {
            $draft = $this->fetchOriginal($draftFolder, $draftUid);
            if ($draft !== null) {
                $to  = implode(', ', array_map(
                    fn($a) => $a['name'] ? "\"{$a['name']}\" <{$a['email']}>" : $a['email'],
                    $draft['to'],
                ));
                $cc  = implode(', ', array_map(
                    fn($a) => $a['name'] ? "\"{$a['name']}\" <{$a['email']}>" : $a['email'],
                    $draft['cc'],
                ));
                $body = $draft['body_html'] !== ''
                    ? $draft['body_html']
                    : $this->toHtml($draft['body_text']);
                return $this->showCompose([
                    'mode'         => 'compose',
                    'to'           => $to,
                    'cc'           => $cc,
                    'subject'      => $draft['subject'] !== '(no subject)' ? $draft['subject'] : '',
                    'body'         => $body,
                    'draftUid'     => $draftUid,
                    'draftFolder'  => $draftFolder,
                ]);
            }
        }

        return $this->showCompose([
            'mode'        => 'compose',
            'to'          => $request->query('to', ''),
            'subject'     => '',
            'body'        => '',
            'cc'          => '',
            'draftUid'    => 0,
            'draftFolder' => '',
        ]);
    }

    public function reply(Request $request, string $folder, string $uid): mixed
    {
        $original = $this->fetchOriginal($folder, (int) $uid);

        if ($original === null) {
            return redirect()->route('inbox');
        }

        $subject = $original['subject'];
        if (!preg_match('/^re:/i', $subject)) {
            $subject = 'Re: ' . $subject;
        }

        $from = $original['from'];
        $replyTo = $from['name']
            ? "\"{$from['name']}\" <{$from['email']}>"
            : $from['email'];

        return $this->showCompose([
            'mode'           => 'reply',
            'to'             => $replyTo,
            'subject'        => $subject,
            'body'           => $this->toHtml($this->quoteForReply($original)),
            'cc'             => '',
            'originalFolder' => $folder,
            'originalUid'    => (int) $uid,
            'draftUid'       => 0,
            'draftFolder'    => '',
        ]);
    }

    public function forward(Request $request, string $folder, string $uid): mixed
    {
        $original = $this->fetchOriginal($folder, (int) $uid);

        if ($original === null) {
            return redirect()->route('inbox');
        }

        $subject = $original['subject'];
        if (!preg_match('/^fwd:/i', $subject)) {
            $subject = 'Fwd: ' . $subject;
        }

        return $this->showCompose([
            'mode'           => 'forward',
            'to'             => '',
            'subject'        => $subject,
            'body'           => $this->toHtml($this->quoteForForward($original)),
            'cc'             => '',
            'originalFolder' => $folder,
            'originalUid'    => (int) $uid,
            'draftUid'       => 0,
            'draftFolder'    => '',
        ]);
    }

    // ------------------------------------------------------------------
    // Send
    // ------------------------------------------------------------------

    public function send(Request $request): mixed
    {
        $maxMb = (int) config('smtp.max_attachment_mb', 25);

        $data = $request->validate([
            'to'            => ['required', 'string', 'max:2000'],
            'cc'            => ['nullable', 'string', 'max:2000'],
            'bcc'           => ['nullable', 'string', 'max:2000'],
            'subject'       => ['nullable', 'string', 'max:998'],
            'body'          => ['nullable', 'string'],
            'attachments'   => ['nullable', 'array'],
            'attachments.*' => ['file', 'max:' . ($maxMb * 1024)],
        ]);

        $attachments = $request->file('attachments', []);
        $totalBytes  = array_sum(array_map(fn($f) => $f->getSize(), $attachments));
        if ($totalBytes > $maxMb * 1024 * 1024) {
            return back()->withInput()->withErrors(['send' => "Total attachment size exceeds {$maxMb} MB."]);
        }

        /** @var ImapGuard $guard */
        $guard    = auth('web');
        $email    = $guard->user()->email;
        $name     = $guard->user()->name;
        $password = $guard->getImapPassword();

        $recipientCount = count(array_filter(
            array_merge(
                preg_split('/[,;]/', $data['to']) ?: [],
                preg_split('/[,;]/', $data['cc'] ?? '') ?: [],
                preg_split('/[,;]/', $data['bcc'] ?? '') ?: [],
            ),
            fn($a) => trim($a) !== '',
        ));

        $limitError = $this->checkSendLimits($email, $recipientCount);
        if ($limitError !== null) {
            return back()->withInput()->withErrors(['send' => $limitError]);
        }

        try {
            $rawMessage = (new SmtpSender())->send(
                fromEmail:    $email,
                fromName:     $name,
                password:     $password,
                to:           $data['to'],
                subject:      $data['subject'] ?? '',
                bodyHtml:     $data['body'] ?? '',
                cc:           $data['cc'] ?? '',
                bcc:          $data['bcc'] ?? '',
                authUsername: $guard->getImapLogin(),
                attachments:  $attachments,
            );

            MailSendLog::record(
                email:          $email,
                recipientCount: max(1, $recipientCount),
                subject:        $data['subject'] ?? '',
                ip:             $request->ip(),
                status:         'sent',
            );

            // Save a copy to the user's Sent folder. Failure here must not
            // surface to the user — the message was already delivered.
            $this->saveToSent($guard, $rawMessage);

            // Delete the draft that was being edited, if any.
            $draftUid    = (int) $request->input('draft_uid', 0);
            $draftFolder = (string) $request->input('draft_folder', '');
            if ($draftUid > 0 && $draftFolder !== '') {
                $this->deleteDraft($guard, $draftFolder, $draftUid);
            }
        } catch (\Throwable $e) {
            MailSendLog::record(
                email:          $email,
                recipientCount: max(1, $recipientCount),
                subject:        $data['subject'] ?? '',
                ip:             $request->ip(),
                status:         'failed',
            );

            return back()
                ->withInput()
                ->withErrors(['send' => 'Could not send message: ' . $e->getMessage()]);
        }

        return redirect()->route('inbox')->with('success', 'Message sent.');
    }

    public function saveDraft(Request $request): mixed
    {
        $data = $request->validate([
            'to'           => ['nullable', 'string', 'max:2000'],
            'cc'           => ['nullable', 'string', 'max:2000'],
            'bcc'          => ['nullable', 'string', 'max:2000'],
            'subject'      => ['nullable', 'string', 'max:998'],
            'body'         => ['nullable', 'string'],
            'draft_uid'    => ['nullable', 'integer', 'min:1'],
            'draft_folder' => ['nullable', 'string', 'max:500'],
        ]);

        /** @var ImapGuard $guard */
        $guard = auth('web');

        $raw = $this->buildDraftRaw(
            fromEmail: $guard->user()->email,
            fromName:  $guard->user()->name ?? '',
            to:        $data['to']      ?? '',
            cc:        $data['cc']      ?? '',
            bcc:       $data['bcc']     ?? '',
            subject:   $data['subject'] ?? '',
            body:      $data['body']    ?? '',
        );

        $imap = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());

            $draftsFolder = $this->resolveDraftsFolder($imap);

            // Delete the previous draft version before appending the new one.
            $oldUid = (int) ($data['draft_uid'] ?? 0);
            if ($oldUid > 0) {
                $prevFolder = $data['draft_folder'] ?? $draftsFolder;
                $imap->selectFolder($prevFolder);
                $imap->deleteMessages((string) $oldUid);
            }

            $newUid = $imap->appendGetUid($draftsFolder, $raw, ['\\Draft', '\\Seen']);

            $imap->logout();
        } catch (\Throwable) {
            $imap->close();
            return response()->json(['ok' => false], 500);
        }

        if ($newUid === -1) {
            return response()->json(['ok' => false], 500);
        }

        return response()->json([
            'ok'     => true,
            'uid'    => $newUid,   // 0 = server has no APPENDUID, >0 = trackable UID
            'folder' => $draftsFolder,
        ]);
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    /**
     * Check whether the authenticated user is allowed to send right now.
     *
     * Returns a human-readable error string when a limit is exceeded,
     * or null when sending is permitted.
     */
    private function checkSendLimits(string $email, int $recipientCount): ?string
    {
        $settings = userSettings();

        // Resolve limits: group overrides global defaults
        if ($settings->group_id) {
            $group    = MailGroup::find($settings->group_id);
            $hourly   = $group?->hourly_limit;
            $daily    = $group?->daily_limit;
            $weekly   = $group?->weekly_limit;
            $monthly  = $group?->monthly_limit;
            $maxRcpt  = $group?->max_recipients;
        } else {
            $hourly   = AdminSetting::get('default_hourly_limit');
            $daily    = AdminSetting::get('default_daily_limit');
            $weekly   = AdminSetting::get('default_weekly_limit');
            $monthly  = AdminSetting::get('default_monthly_limit');
            $maxRcpt  = AdminSetting::get('default_max_recipients');
        }

        // Per-message recipient cap
        if ($maxRcpt !== null && $recipientCount > (int) $maxRcpt) {
            return "You can address at most {$maxRcpt} recipients per message (you have {$recipientCount}).";
        }

        $now  = Carbon::now();
        $base = MailSendLog::where('email', $email)->where('status', 'sent');

        if ($hourly !== null) {
            $count = (clone $base)->where('created_at', '>=', $now->copy()->subHour())->count();
            if ($count >= (int) $hourly) {
                return "Hourly sending limit of {$hourly} reached. Please try again later.";
            }
        }

        if ($daily !== null) {
            $count = (clone $base)->where('created_at', '>=', $now->copy()->startOfDay())->count();
            if ($count >= (int) $daily) {
                return "Daily sending limit of {$daily} reached.";
            }
        }

        if ($weekly !== null) {
            $count = (clone $base)->where('created_at', '>=', $now->copy()->startOfWeek())->count();
            if ($count >= (int) $weekly) {
                return "Weekly sending limit of {$weekly} reached.";
            }
        }

        if ($monthly !== null) {
            $count = (clone $base)->where('created_at', '>=', $now->copy()->startOfMonth())->count();
            if ($count >= (int) $monthly) {
                return "Monthly sending limit of {$monthly} reached.";
            }
        }

        return null;
    }

    private function showCompose(array $compose): mixed
    {
        /** @var ImapGuard $guard */
        $guard    = auth('web');
        $settings = userSettings();
        $folders  = $this->fetchFolders($guard);

        // Inject signature — placed before any quoted body text
        $sig = trim($settings->signature ?? '');
        if ($sig !== '') {
            $sigBlock          = "\n\n-- \n{$sig}";
            $existing          = $compose['body'];
            $compose['body']   = $existing !== ''
                ? $sigBlock . "\n\n" . $existing
                : $sigBlock;
        }

        return view(mailView('compose.index'), array_merge($compose, [
            'folders'       => $folders,
            'currentFolder' => '',
            'fromEmail'     => $guard->user()->email,
            'fromName'      => $settings->display_name ?: $guard->user()->name,
            'draftUid'      => $compose['draftUid']    ?? 0,
            'draftFolder'   => $compose['draftFolder'] ?? '',
        ]));
    }

    /**
     * APPEND the just-sent message to the user's Sent folder. Creates the
     * folder if it doesn't exist. Silent on failure — delivery already
     * succeeded by the time this runs.
     */
    private function saveToSent(ImapGuard $guard, string $rawMessage): void
    {
        $imap = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());

            $sentFolder = $this->resolveSentFolder($imap);

            // APPEND with \Seen so it doesn't show as unread in Sent.
            if (!$imap->appendMessage($sentFolder, $rawMessage, ['\\Seen'])) {
                // First attempt failed — folder may not exist. Try to create it then retry once.
                if ($imap->createFolder($sentFolder)) {
                    $imap->appendMessage($sentFolder, $rawMessage, ['\\Seen']);
                }
            }

            $imap->logout();
        } catch (\Throwable) {
            $imap->close();
        }
    }

    /**
     * Delete a single draft message. Silent on failure.
     */
    private function deleteDraft(ImapGuard $guard, string $folder, int $uid): void
    {
        $imap = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $imap->selectFolder($folder);
            $imap->deleteMessages((string) $uid);
            $imap->logout();
        } catch (\Throwable) {
            $imap->close();
        }
    }

    /**
     * Build a minimal RFC 5322 message suitable for saving as a draft.
     * Uses Symfony Mime so encoding and header folding are handled correctly.
     */
    private function buildDraftRaw(
        string $fromEmail,
        string $fromName,
        string $to,
        string $cc,
        string $bcc,
        string $subject,
        string $body,
    ): string {
        $htmlBody  = $body !== '' ? $body : '<p><br></p>';
        $plainBody = strip_tags(str_replace(['</p>', '<br>', '<br/>', '<br />'], "\n", $htmlBody));

        $email = (new Email())
            ->from(new Address($fromEmail, $fromName ?: $fromEmail))
            ->subject($subject ?: '(no subject)')
            ->html($htmlBody)
            ->text(trim($plainBody));

        foreach ($this->splitAddresses($to)  as $a) { $email->addTo($a); }
        foreach ($this->splitAddresses($cc)  as $a) { $email->addCc($a); }
        foreach ($this->splitAddresses($bcc) as $a) { $email->addBcc($a); }

        return $email->toString();
    }

    /**
     * Parse a comma/semicolon-separated address string into Symfony Address objects.
     *
     * @return Address[]
     */
    private function splitAddresses(string $raw): array
    {
        if (trim($raw) === '') {
            return [];
        }
        $addresses = [];
        foreach (preg_split('/[,;]/', $raw) ?: [] as $part) {
            $part = trim($part);
            if ($part === '') {
                continue;
            }
            try {
                if (preg_match('/^"?(.+?)"?\s*<([^>]+)>$/', $part, $m)) {
                    $addresses[] = new Address(trim($m[2]), trim($m[1], ' "'));
                } else {
                    $addresses[] = new Address($part);
                }
            } catch (\Throwable) {
                // Skip malformed addresses rather than aborting the draft save.
            }
        }
        return $addresses;
    }

    /**
     * Find the Drafts folder by SPECIAL-USE \Drafts attribute, falling back
     * to common naming conventions, then plain "Drafts".
     */
    private function resolveDraftsFolder(ImapConnection $imap): string
    {
        try {
            $folders = $imap->listFolders();
        } catch (\Throwable) {
            return 'Drafts';
        }

        foreach ($folders as $folder) {
            if (in_array('\\drafts', $folder['attributes'], true)) {
                return $folder['name'];
            }
        }

        $candidates = ['Drafts', 'INBOX.Drafts', 'Draft'];
        foreach ($candidates as $candidate) {
            foreach ($folders as $folder) {
                if (strcasecmp($folder['name'], $candidate) === 0) {
                    return $folder['name'];
                }
            }
        }

        return 'Drafts';
    }

    /**
     * Find the user's Sent folder by SPECIAL-USE \Sent attribute, falling
     * back to common naming conventions, then plain "Sent".
     */
    private function resolveSentFolder(ImapConnection $imap): string
    {
        try {
            $folders = $imap->listFolders();
        } catch (\Throwable) {
            return 'Sent';
        }

        // 1. Server-advertised \Sent SPECIAL-USE attribute.
        foreach ($folders as $folder) {
            if (in_array('\\sent', $folder['attributes'], true)) {
                return $folder['name'];
            }
        }

        // 2. Common case-insensitive names (covers Sent, Sent Items, INBOX.Sent).
        $candidates = ['Sent', 'INBOX.Sent', 'Sent Items', 'Sent Messages'];
        foreach ($candidates as $candidate) {
            foreach ($folders as $folder) {
                if (strcasecmp($folder['name'], $candidate) === 0) {
                    return $folder['name'];
                }
            }
        }

        return 'Sent';
    }

    private function fetchFolders(ImapGuard $guard): array
    {
        $imap = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $folders = array_map(
                fn(array $f) => array_merge($f, $imap->getFolderStatus($f['name'])),
                $imap->listFolders()
            );
            $imap->logout();
            return $folders;
        } catch (\Throwable) {
            $imap->close();
            return [];
        }
    }

    private function fetchOriginal(string $folder, int $uid): ?array
    {
        /** @var ImapGuard $guard */
        $guard    = auth('web');
        $imap     = new ImapConnection();

        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $imap->selectFolder($folder);
            $fetched = $imap->fetchMessageRaw($uid);
            $imap->logout();
        } catch (\Throwable) {
            $imap->close();
            return null;
        }

        if ($fetched['raw'] === '') {
            return null;
        }

        $parsed            = (new MimeParser())->parse($fetched['raw']);
        $parsed['uid']     = $uid;
        $parsed['folder']  = $folder;

        try {
            $dt = Carbon::parse($parsed['date_raw']);
            $parsed['date_formatted'] = $dt->format('l, F j, Y \a\t g:i A');
        } catch (\Throwable) {
            $parsed['date_formatted'] = $parsed['date_raw'];
        }

        return $parsed;
    }

    /**
     * Convert a plain-text body to simple HTML suitable for the rich-text editor.
     * Lines starting with "> " become <blockquote> content.
     * Already-HTML strings (start with a tag) are returned unchanged.
     */
    private function toHtml(string $text): string
    {
        if ($text === '') {
            return '';
        }
        if (preg_match('/^\s*</s', $text)) {
            return $text;
        }

        $lines     = explode("\n", $text);
        $out       = '';
        $quoteLines = [];

        foreach ($lines as $line) {
            if (str_starts_with($line, '> ') || $line === '>') {
                $quoteLines[] = htmlspecialchars(substr($line, 2), ENT_QUOTES | ENT_HTML5, 'UTF-8');
            } else {
                if ($quoteLines !== []) {
                    $out .= '<blockquote>' . implode('<br>', $quoteLines) . '</blockquote>';
                    $quoteLines = [];
                }
                $escaped = htmlspecialchars($line, ENT_QUOTES | ENT_HTML5, 'UTF-8');
                $out .= $escaped !== '' ? '<p>' . $escaped . '</p>' : '<p><br></p>';
            }
        }
        if ($quoteLines !== []) {
            $out .= '<blockquote>' . implode('<br>', $quoteLines) . '</blockquote>';
        }

        return $out;
    }

    private function quoteForReply(array $original): string
    {
        $date    = $original['date_formatted'] ?? $original['date_raw'];
        $from    = $original['from'];
        $sender  = $from['name'] ? "{$from['name']} <{$from['email']}>" : $from['email'];
        $body    = $this->plainBody($original);

        $quoted  = implode("\n", array_map(
            static fn(string $line): string => '> ' . $line,
            explode("\n", $body),
        ));

        return "\n\nOn {$date}, {$sender} wrote:\n{$quoted}";
    }

    private function quoteForForward(array $original): string
    {
        $date   = $original['date_formatted'] ?? $original['date_raw'];
        $from   = $original['from'];
        $sender = $from['name'] ? "{$from['name']} <{$from['email']}>" : $from['email'];
        $to     = implode(', ', array_map(
            static fn(array $a): string => $a['name'] ? "{$a['name']} <{$a['email']}>" : $a['email'],
            $original['to'],
        ));
        $body   = $this->plainBody($original);

        return "\n\n---------- Forwarded message ----------\n"
            . "From: {$sender}\n"
            . "Date: {$date}\n"
            . "Subject: {$original['subject']}\n"
            . "To: {$to}\n\n"
            . $body;
    }

    /** Get the best plain-text representation of a message body. */
    private function plainBody(array $message): string
    {
        if ($message['body_text'] !== '') {
            return rtrim($message['body_text']);
        }
        if ($message['body_html'] !== '') {
            return rtrim(wordwrap(strip_tags($message['body_html']), 80));
        }
        return '';
    }
}
