<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Models\ContactGroup;
use Illuminate\Http\Request;

class ContactGroupController extends Controller
{
    public function store(Request $request): mixed
    {
        $data = $request->validate([
            'name'  => ['required', 'string', 'max:100'],
            'color' => ['required', 'string', 'in:' . implode(',', array_keys(ContactGroup::COLORS))],
        ]);

        ContactGroup::create([
            'owner_email' => auth('web')->user()->email,
            'name'        => $data['name'],
            'color'       => $data['color'],
        ]);

        return redirect()->back()->with('success', 'Group created.');
    }

    public function update(Request $request, ContactGroup $contactGroup): mixed
    {
        abort_unless($contactGroup->owner_email === auth('web')->user()->email, 403);

        $data = $request->validate([
            'name'  => ['required', 'string', 'max:100'],
            'color' => ['required', 'string', 'in:' . implode(',', array_keys(ContactGroup::COLORS))],
        ]);

        $contactGroup->update($data);

        return redirect()->back()->with('success', 'Group updated.');
    }

    public function destroy(ContactGroup $contactGroup): mixed
    {
        abort_unless($contactGroup->owner_email === auth('web')->user()->email, 403);
        $contactGroup->delete();

        return redirect()->route('contacts')->with('success', 'Group deleted.');
    }
}
