<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index(): mixed
    {
        $contacts = Contact::where('owner_email', $this->ownerEmail())
            ->orderBy('name')
            ->orderBy('email')
            ->get();

        return view(mailView('contacts.index'), [
            'contacts'      => $contacts,
            'folders'       => [],
            'currentFolder' => '',
        ]);
    }

    public function store(Request $request): mixed
    {
        $data = $request->validate([
            'name'  => ['nullable', 'string', 'max:255'],
            'email' => ['required', 'email', 'max:255'],
            'phone' => ['nullable', 'string', 'max:50'],
            'notes' => ['nullable', 'string', 'max:2000'],
        ]);

        Contact::updateOrCreate(
            ['owner_email' => $this->ownerEmail(), 'email' => $data['email']],
            ['name' => $data['name'] ?? '', 'phone' => $data['phone'] ?? '', 'notes' => $data['notes'] ?? ''],
        );

        return redirect()->route('contacts')->with('success', 'Contact saved.');
    }

    public function show(Contact $contact): mixed
    {
        $this->authorise($contact);

        return view(mailView('contacts.show'), [
            'contact'       => $contact,
            'folders'       => [],
            'currentFolder' => '',
        ]);
    }

    public function update(Request $request, Contact $contact): mixed
    {
        $this->authorise($contact);

        $data = $request->validate([
            'name'  => ['nullable', 'string', 'max:255'],
            'email' => ['required', 'email', 'max:255'],
            'phone' => ['nullable', 'string', 'max:50'],
            'notes' => ['nullable', 'string', 'max:2000'],
        ]);

        $contact->update([
            'name'  => $data['name']  ?? '',
            'email' => $data['email'],
            'phone' => $data['phone'] ?? '',
            'notes' => $data['notes'] ?? '',
        ]);

        return redirect()->route('contacts')->with('success', 'Contact updated.');
    }

    public function destroy(Contact $contact): mixed
    {
        $this->authorise($contact);
        $contact->delete();

        return redirect()->route('contacts')->with('success', 'Contact deleted.');
    }

    /**
     * JSON endpoint for compose autocomplete.
     * GET /contacts/search?q=...
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function autocomplete(Request $request): mixed
    {
        $q = trim($request->get('q', ''));

        if (strlen($q) < 2) {
            return response()->json([]);
        }

        $contacts = Contact::where('owner_email', $this->ownerEmail())
            ->where(function ($query) use ($q) {
                $query->where('name', 'like', "%{$q}%")
                      ->orWhere('email', 'like', "%{$q}%");
            })
            ->orderBy('name')
            ->limit(10)
            ->get(['name', 'email']);

        return response()->json($contacts);
    }

    // ------------------------------------------------------------------

    private function ownerEmail(): string
    {
        return auth('web')->user()->email;
    }

    private function authorise(Contact $contact): void
    {
        abort_unless($contact->owner_email === $this->ownerEmail(), 403);
    }
}
