<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapGuard;
use App\Services\ImapConnection;
use App\Services\MailboxListCache;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class FolderController extends Controller
{
    // ------------------------------------------------------------------
    // IMAP helpers
    // ------------------------------------------------------------------

    private function connectImap(): ImapConnection
    {
        /** @var ImapGuard $guard */
        $guard = auth('web');
        $imap  = new ImapConnection();
        $imap->connect(
            host:         config('imap.host'),
            port:         config('imap.port'),
            encryption:   config('imap.encryption'),
            validateCert: config('imap.validate_cert', false),
            timeout:      config('imap.timeout', 10),
        );
        $imap->login($guard->getImapLogin(), $guard->getImapPassword());
        return $imap;
    }

    /**
     * Return true if $name is INBOX or has a system-use IMAP attribute
     * (\\Sent, \\Drafts, \\Trash, \\Junk, \\Archive, \\Spam).
     * These folders must not be renamed or deleted by users.
     */
    private function isSystemFolder(ImapConnection $imap, string $name): bool
    {
        if (strtoupper($name) === 'INBOX') {
            return true;
        }

        $systemAttrs = ['\\sent', '\\drafts', '\\trash', '\\junk', '\\archive', '\\spam'];

        foreach ($imap->listFolders() as $f) {
            if ($f['name'] === $name) {
                foreach ($systemAttrs as $attr) {
                    if (in_array($attr, $f['attributes'], true)) {
                        return true;
                    }
                }
            }
        }

        return false;
    }

    // ------------------------------------------------------------------
    // Actions
    // ------------------------------------------------------------------

    /**
     * Create a new custom folder.
     */
    public function store(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'name' => ['required', 'string', 'min:1', 'max:100', 'regex:/^[a-zA-Z0-9][a-zA-Z0-9 ._\-\[\]()]*$/'],
        ], [
            'name.regex' => 'Folder name may only contain letters, numbers, spaces, dots, hyphens, underscores, brackets, and parentheses.',
        ]);

        $imap = null;
        try {
            $imap = $this->connectImap();
            $ok   = $imap->createFolder($validated['name']);
            $imap->logout();
        } catch (\Throwable) {
            if ($imap) $imap->close();
            return back()->with('error', 'Could not connect to mail server.');
        }

        if (!$ok) {
            return back()->with('error', 'Could not create folder. It may already exist.');
        }

        /** @var ImapGuard $guard */
        $guard = auth('web');
        MailboxListCache::forget(auth('web')->getImapLogin());

        return back()->with('success', 'Folder "' . $validated['name'] . '" created.');
    }

    /**
     * Rename an existing custom folder.
     * All data is in the request body; no route parameter is used because
     * folder names may contain slashes (hierarchy delimiter).
     */
    public function update(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'old_name' => 'required|string|max:200',
            'new_name' => ['required', 'string', 'min:1', 'max:100', 'regex:/^[a-zA-Z0-9][a-zA-Z0-9 ._\-\[\]()]*$/'],
        ], [
            'new_name.regex' => 'Folder name may only contain letters, numbers, spaces, dots, hyphens, underscores, brackets, and parentheses.',
        ]);

        $imap = null;
        try {
            $imap = $this->connectImap();

            if ($this->isSystemFolder($imap, $validated['old_name'])) {
                $imap->logout();
                return back()->with('error', 'System folders cannot be renamed.');
            }

            $ok = $imap->renameFolder($validated['old_name'], $validated['new_name']);
            $imap->logout();
        } catch (\Throwable) {
            if ($imap) $imap->close();
            return back()->with('error', 'Could not connect to mail server.');
        }

        if (!$ok) {
            return back()->with('error', 'Could not rename folder.');
        }

        MailboxListCache::forget(auth('web')->getImapLogin());

        return redirect()->route('folder', ['folder' => rawurlencode($validated['new_name'])])
            ->with('success', 'Folder renamed to "' . $validated['new_name'] . '".');
    }

    /**
     * Delete a custom folder.
     * Folder name is in the request body (not a route segment) for the same reason.
     */
    public function destroy(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'name' => 'required|string|max:200',
        ]);

        $imap = null;
        try {
            $imap = $this->connectImap();

            if ($this->isSystemFolder($imap, $validated['name'])) {
                $imap->logout();
                return back()->with('error', 'System folders cannot be deleted.');
            }

            $ok = $imap->deleteFolder($validated['name']);
            $imap->logout();
        } catch (\Throwable) {
            if ($imap) $imap->close();
            return back()->with('error', 'Could not connect to mail server.');
        }

        if (!$ok) {
            return back()->with('error', 'Could not delete folder. Make sure it contains no messages.');
        }

        MailboxListCache::forget(auth('web')->getImapLogin());

        return redirect()->route('inbox')
            ->with('success', 'Folder "' . $validated['name'] . '" deleted.');
    }
}
