<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapGuard;
use App\Services\ImapConnection;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class InboxController extends Controller
{
    private const PER_PAGE = 50;

    public function index(Request $request): mixed
    {
        return $this->showFolder('INBOX', $request);
    }

    public function folder(Request $request, string $folder): mixed
    {
        return $this->showFolder($folder, $request);
    }

    // ------------------------------------------------------------------

    private function showFolder(string $folder, Request $request): mixed
    {
        /** @var ImapGuard $guard */
        $guard    = auth('web');
        $password = $guard->getImapPassword();
        $login    = $guard->getImapLogin();

        $imap = new ImapConnection();

        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );

            $imap->login($login, $password);

            // Folders for sidebar — fetch STATUS (unseen) for each
            $rawFolders = $imap->listFolders();
            $folders    = array_map(
                fn(array $f) => array_merge($f, $imap->getFolderStatus($f['name'])),
                $rawFolders
            );

            // Select the requested folder and fetch headers
            $stats    = $imap->selectFolder($folder);
            $total    = $stats['exists'];
            $messages = [];

            if ($total > 0) {
                $from     = max(1, $total - self::PER_PAGE + 1);
                $messages = $imap->fetchMessageHeaders("{$from}:{$total}");
                $messages = $this->formatDates($messages);
            }

            $imap->logout();

        } catch (\Throwable $e) {
            $imap->close();
            return view(mailView('inbox.index'), [
                'error'         => $e->getMessage(),
                'folders'       => [],
                'currentFolder' => $folder,
                'messages'      => [],
                'total'         => 0,
            ]);
        }

        return view(mailView('inbox.index'), [
            'folders'       => $folders,
            'currentFolder' => $folder,
            'messages'      => $messages,
            'total'         => $total,
        ]);
    }

    /** Add a human-readable date_formatted field to each message. */
    private function formatDates(array $messages): array
    {
        $now = Carbon::now();

        return array_map(function (array $msg) use ($now): array {
            try {
                $dt = Carbon::parse($msg['date_raw']);
                $msg['date_formatted'] = $dt->isToday()
                    ? $dt->format('g:i A')
                    : ($dt->isSameYear($now) ? $dt->format('M j') : $dt->format('M j, Y'));
            } catch (\Throwable) {
                $msg['date_formatted'] = $msg['date_raw'];
            }
            return $msg;
        }, $messages);
    }
}
