<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapGuard;
use App\Services\ImapConnection;
use App\Services\MimeParser;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class MessageController extends Controller
{
    public function show(Request $request, string $folder, string $uid): mixed
    {
        /** @var ImapGuard $guard */
        $guard    = auth('web');
        $password = $guard->getImapPassword();
        $login    = $guard->getImapLogin();
        $uidInt   = (int) $uid;

        $imap = new ImapConnection();

        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($login, $password);

            // Folders for sidebar
            $folders = array_map(
                fn(array $f) => array_merge($f, $imap->getFolderStatus($f['name'])),
                $imap->listFolders()
            );

            $imap->selectFolder($folder);

            $fetched = $imap->fetchMessageRaw($uidInt);
            $imap->markSeen($uidInt);
            $imap->logout();

        } catch (\Throwable $e) {
            $imap->close();
            $backRoute = strtoupper($folder) === 'INBOX'
                ? route('inbox')
                : route('folder', ['folder' => rawurlencode($folder)]);
            return redirect($backRoute)->withErrors(['message' => 'Could not load message: ' . $e->getMessage()]);
        }

        if ($fetched['raw'] === '') {
            return redirect()->route('inbox');
        }

        $parser  = new MimeParser();
        $message = $parser->parse($fetched['raw']);

        $message['uid']            = $uidInt;
        $message['folder']         = $folder;
        $message['flags']          = $fetched['flags'];
        $message['date_formatted'] = $this->formatDate($message['date_raw']);

        $receiptSetting = userSettings()->read_receipt ?? 'ask';
        $receiptTo      = $message['receipt_to']['email'] ?? '';

        return view(mailView('inbox.message'), [
            'folders'        => $folders,
            'currentFolder'  => $folder,
            'message'        => $message,
            'receiptTo'      => $receiptTo,
            'receiptSetting' => $receiptSetting,
        ]);
    }

    public function print(Request $request, string $folder, string $uid): mixed
    {
        /** @var \App\Auth\ImapGuard $guard */
        $guard  = auth('web');
        $uidInt = (int) $uid;

        $imap = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $imap->selectFolder($folder);
            $fetched = $imap->fetchMessageRaw($uidInt);
            $imap->logout();
        } catch (\Throwable $e) {
            $imap->close();
            return redirect()->route('inbox')->withErrors(['message' => $e->getMessage()]);
        }

        if ($fetched['raw'] === '') {
            return redirect()->route('inbox');
        }

        $parser  = new MimeParser();
        $message = $parser->parse($fetched['raw']);

        $message['uid']            = $uidInt;
        $message['folder']         = $folder;
        $message['flags']          = $fetched['flags'];
        $message['date_formatted'] = $this->formatDate($message['date_raw']);

        return view(mailView('inbox.print'), compact('message'));
    }

    public function destroy(Request $request, string $folder, string $uid): mixed
    {
        $this->imapAction(function (ImapConnection $imap) use ($folder, $uid) {
            $imap->selectFolder($folder);
            $imap->deleteMessages((string)(int)$uid);
        });

        $back = strtoupper($folder) === 'INBOX'
            ? route('inbox')
            : route('folder', ['folder' => rawurlencode($folder)]);

        return $request->expectsJson()
            ? response()->json(['ok' => true])
            : redirect($back);
    }

    public function move(Request $request, string $folder, string $uid): mixed
    {
        $target = $request->input('target');
        if (!$target) {
            return response()->json(['error' => 'target required'], 422);
        }

        $this->imapAction(function (ImapConnection $imap) use ($folder, $uid, $target) {
            $imap->selectFolder($folder);
            $imap->moveMessages((string)(int)$uid, $target);
        });

        return response()->json(['ok' => true]);
    }

    public function flag(Request $request, string $folder, string $uid): mixed
    {
        $flag = $request->input('flag', '\\Flagged');
        $add  = (bool) $request->input('add', true);

        $this->imapAction(function (ImapConnection $imap) use ($folder, $uid, $flag, $add) {
            $imap->selectFolder($folder);
            $imap->storeFlags((string)(int)$uid, $flag, $add);
        });

        return response()->json(['ok' => true]);
    }

    // ------------------------------------------------------------------

    private function imapAction(callable $fn): void
    {
        /** @var \App\Auth\ImapGuard $guard */
        $guard = auth('web');
        $imap  = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $fn($imap);
            $imap->logout();
        } catch (\Throwable) {
            $imap->close();
        }
    }

    // ------------------------------------------------------------------

    private function formatDate(string $raw): string
    {
        if ($raw === '') {
            return '';
        }
        try {
            $dt = Carbon::parse($raw);
            return $dt->format('l, F j, Y \a\t g:i A');
        } catch (\Throwable) {
            return $raw;
        }
    }
}
