<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapGuard;
use App\Models\EmailNote;
use App\Models\KnownSender;
use App\Models\ReplyLaterEmail;
use App\Models\SenderStat;
use App\Models\SetAsideEmail;
use App\Models\SnoozedEmail;
use App\Services\ContentSanitizer;
use App\Services\ImapConnection;
use App\Services\MailboxListCache;
use App\Services\MimeParser;
use App\Services\SenderReputation;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class MessageController extends Controller
{
    public function show(Request $request, string $folder, string $uid): mixed
    {
        /** @var ImapGuard $guard */
        $guard    = auth('web');
        $password = $guard->getImapPassword();
        $login    = $guard->getImapLogin();
        $uidInt   = (int) $uid;

        $imap = new ImapConnection();

        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($login, $password);

            // Folders for sidebar - cached 30s per user. Saves 1 + N IMAP
            // round trips per page load (LIST + STATUS per folder).
            $folders = MailboxListCache::get($login, fn () => array_map(
                fn (array $f) => array_merge($f, $imap->getFolderStatus($f['name'])),
                $imap->listFolders()
            ));

            $imap->selectFolder($folder);

            $fetched = $imap->fetchMessageRaw($uidInt);
            $imap->markSeen($uidInt);
            $imap->logout();

        } catch (\Throwable $e) {
            $imap->close();
            $backRoute = strtoupper($folder) === 'INBOX'
                ? route('inbox')
                : route('folder', ['folder' => rawurlencode($folder)]);
            return redirect($backRoute)->withErrors(['message' => 'Could not load message: ' . $e->getMessage()]);
        }

        if ($fetched['raw'] === '') {
            return redirect()->route('inbox');
        }

        $parser  = new MimeParser();
        $message = $parser->parse($fetched['raw']);

        $message['uid']            = $uidInt;
        $message['folder']         = $folder;
        $message['flags']          = $fetched['flags'];
        $message['date_formatted'] = $this->formatDate($message['date_raw']);

        $receiptSetting = userSettings()->read_receipt ?? 'ask';
        $receiptTo      = $message['receipt_to']['email'] ?? '';

        $userEmail  = auth('web')->user()->email;
        $senderEmail = strtolower($message['from']['email'] ?? '');

        // Sanitize the HTML body: neutralise spy pixels + strip
        // tracking params from links before render.
        $sanitizer = new ContentSanitizer();
        if ($message['body_html'] !== '') {
            $message['body_html'] = $sanitizer->sanitize($message['body_html']);
        }
        $message['spy_pixels_blocked']  = $sanitizer->spyPixelCount;
        $message['trackers_cleaned']    = $sanitizer->cleanedLinkCount;

        // Bump received counter for this sender. We only count a single
        // 'received' per uid by checking whether SenderStat existed
        // before this view; first_seen_at on creation means this is
        // an idempotent enough proxy for new-message arrival.
        //
        // Pushed to the queue so the message view does not pay for the
        // 3 DB queries SenderStat::bump runs (SELECT + maybe INSERT +
        // UPDATE). The badge below reads previously persisted counters;
        // a second of staleness on this very bump is invisible.
        if ($senderEmail) {
            \App\Jobs\BumpSenderStat::dispatch($userEmail, $senderEmail, 'received_count', 1, 'last_received_at');
        }

        $note        = EmailNote::where('user_email', $userEmail)->where('imap_uid', $uidInt)->where('mailbox', $folder)->first();
        $isSnoozed   = SnoozedEmail::isSnoozed($userEmail, $uidInt, $folder);
        $isSetAside  = SetAsideEmail::where('user_email', $userEmail)->where('imap_uid', $uidInt)->where('mailbox', $folder)->exists();
        $isReplyLater= ReplyLaterEmail::where('user_email', $userEmail)->where('imap_uid', $uidInt)->where('mailbox', $folder)->exists();
        $isKnownSender = KnownSender::isKnown($userEmail, $senderEmail);

        // Trust badge.
        $senderBadge = (new SenderReputation())->badgeFor($userEmail, $senderEmail);

        return view(mailView('inbox.message'), [
            'folders'        => $folders,
            'currentFolder'  => $folder,
            'message'        => $message,
            'receiptTo'      => $receiptTo,
            'receiptSetting' => $receiptSetting,
            'note'           => $note,
            'isSnoozed'      => $isSnoozed,
            'isSetAside'     => $isSetAside,
            'isReplyLater'   => $isReplyLater,
            'isKnownSender'  => $isKnownSender,
            'senderBadge'    => $senderBadge,
        ]);
    }

    public function print(Request $request, string $folder, string $uid): mixed
    {
        /** @var \App\Auth\ImapGuard $guard */
        $guard  = auth('web');
        $uidInt = (int) $uid;

        $imap = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $imap->selectFolder($folder);
            $fetched = $imap->fetchMessageRaw($uidInt);
            $imap->logout();
        } catch (\Throwable $e) {
            $imap->close();
            return redirect()->route('inbox')->withErrors(['message' => $e->getMessage()]);
        }

        if ($fetched['raw'] === '') {
            return redirect()->route('inbox');
        }

        $parser  = new MimeParser();
        $message = $parser->parse($fetched['raw']);

        $message['uid']            = $uidInt;
        $message['folder']         = $folder;
        $message['flags']          = $fetched['flags'];
        $message['date_formatted'] = $this->formatDate($message['date_raw']);

        return view(mailView('inbox.print'), compact('message'));
    }

    public function destroy(Request $request, string $folder, string $uid): mixed
    {
        $this->imapAction(function (ImapConnection $imap) use ($folder, $uid) {
            $trash = $this->findTrashFolder($imap, $folder);

            if ($trash === null) {
                // Already in Trash (or no Trash folder) — permanently delete
                $imap->selectFolder($folder);
                $imap->deleteMessages((string)(int)$uid);
            } else {
                // Move to Trash
                $imap->selectFolder($folder);
                $imap->moveMessages((string)(int)$uid, $trash);
            }
        });

        $back = strtoupper($folder) === 'INBOX'
            ? route('inbox')
            : route('folder', ['folder' => rawurlencode($folder)]);

        return $request->expectsJson()
            ? response()->json(['ok' => true])
            : redirect($back);
    }

    public function move(Request $request, string $folder, string $uid): mixed
    {
        $target = $request->input('target');
        if (!$target) {
            return response()->json(['error' => 'target required'], 422);
        }

        $this->imapAction(function (ImapConnection $imap) use ($folder, $uid, $target) {
            $imap->selectFolder($folder);
            $imap->moveMessages((string)(int)$uid, $target);
        });

        return response()->json(['ok' => true]);
    }

    public function flag(Request $request, string $folder, string $uid): mixed
    {
        $flag = $request->input('flag', '\\Flagged');
        $add  = (bool) $request->input('add', true);

        $this->imapAction(function (ImapConnection $imap) use ($folder, $uid, $flag, $add) {
            $imap->selectFolder($folder);
            $imap->storeFlags((string)(int)$uid, $flag, $add);
        });

        return response()->json(['ok' => true]);
    }

    // ------------------------------------------------------------------

    private function imapAction(callable $fn): void
    {
        /** @var \App\Auth\ImapGuard $guard */
        $guard = auth('web');
        $imap  = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $fn($imap);
            $imap->logout();
        } catch (\Throwable) {
            $imap->close();
        }
    }

    /**
     * Find the Trash folder name. Returns null if $currentFolder IS already Trash,
     * so the caller knows to permanently delete instead of move.
     */
    private function findTrashFolder(ImapConnection $imap, string $currentFolder): ?string
    {
        $folders = $imap->listFolders();

        // Look for \Trash special-use attribute first
        foreach ($folders as $f) {
            foreach ($f['attributes'] as $attr) {
                if (strtolower($attr) === '\\trash') {
                    $trash = $f['name'];
                    return strtolower($currentFolder) === strtolower($trash) ? null : $trash;
                }
            }
        }

        // Fallback: common name patterns
        $patterns = ['trash', 'deleted', 'deleted messages', 'deleted items'];
        foreach ($folders as $f) {
            $name = strtolower($f['name']);
            foreach ($patterns as $p) {
                if ($name === $p || str_ends_with($name, '/' . $p)) {
                    return strtolower($currentFolder) === $name ? null : $f['name'];
                }
            }
        }

        // No Trash folder found — permanent delete
        return null;
    }

    // ------------------------------------------------------------------

    private function formatDate(string $raw): string
    {
        if ($raw === '') {
            return '';
        }
        try {
            $dt = Carbon::parse($raw);
            return $dt->format('l, F j, Y \a\t g:i A');
        } catch (\Throwable) {
            return $raw;
        }
    }
}
