<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapGuard;
use App\Services\ImapConnection;
use App\Services\MimeParser;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Symfony\Component\Mailer\Transport\Smtp\EsmtpTransport;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mime\Address;

class ReadReceiptController extends Controller
{
    public function send(Request $request, string $folder, string $uid): JsonResponse
    {
        /** @var ImapGuard $guard */
        $guard = auth('web');

        $imap = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $imap->selectFolder($folder);
            $fetched = $imap->fetchMessageRaw((int) $uid);
            $imap->logout();
        } catch (\Throwable $e) {
            $imap->close();
            return response()->json(['error' => $e->getMessage()], 503);
        }

        $parser  = new MimeParser();
        $message = $parser->parse($fetched['raw']);

        $receiptTo = $message['receipt_to']['email'] ?? '';
        if ($receiptTo === '') {
            return response()->json(['error' => 'No receipt address found.'], 422);
        }

        $fromEmail = $guard->user()->email;
        $fromName  = userSettings()->display_name ?: $fromEmail;
        $msgId     = $message['message_id'] ?? '';
        $subject   = $message['subject'] ?? '';

        try {
            $this->sendMdn($fromEmail, $fromName, $receiptTo, $msgId, $subject);
        } catch (\Throwable $e) {
            return response()->json(['error' => 'Could not send receipt: ' . $e->getMessage()], 500);
        }

        return response()->json(['ok' => true]);
    }

    private function sendMdn(
        string $fromEmail,
        string $fromName,
        string $toEmail,
        string $originalMsgId,
        string $originalSubject,
    ): void {
        $transport = $this->buildTransport($fromEmail);

        $humanPart = "Your message \"{$originalSubject}\" was read.";

        $mdnPart = "Reporting-UA: Opterius Mail\r\n"
            . "Final-Recipient: rfc822; {$fromEmail}\r\n"
            . "Original-Message-ID: {$originalMsgId}\r\n"
            . "Disposition: manual-action/MDN-sent-manually; displayed\r\n";

        $boundary = 'mdn_' . bin2hex(random_bytes(8));

        $rawBody = "--{$boundary}\r\n"
            . "Content-Type: text/plain; charset=utf-8\r\n\r\n"
            . $humanPart . "\r\n"
            . "--{$boundary}\r\n"
            . "Content-Type: message/disposition-notification\r\n\r\n"
            . $mdnPart
            . "--{$boundary}--\r\n";

        $email = (new Email())
            ->from(new Address($fromEmail, $fromName))
            ->to($toEmail)
            ->subject("Read: {$originalSubject}")
            ->contentType("multipart/report; report-type=disposition-notification; boundary=\"{$boundary}\"");

        $email->setBody(new \Symfony\Component\Mime\Part\TextPart($rawBody, 'utf-8', 'plain'));

        (new \Symfony\Component\Mailer\Mailer($transport))->send($email);
    }

    private function buildTransport(string $fromEmail): EsmtpTransport
    {
        $host = config('smtp.host', config('imap.host'));
        $port = (int) config('smtp.port', 587);
        $enc  = strtolower((string) config('smtp.encryption', ''));
        $tls  = $enc === 'tls';

        /** @var ImapGuard $guard */
        $guard = auth('web');

        $transport = new EsmtpTransport($host, $port, $tls);
        $transport->setUsername($guard->getImapLogin());
        $transport->setPassword($guard->getImapPassword());

        return $transport;
    }
}
