<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapGuard;
use App\Services\ImapConnection;
use App\Services\MailboxListCache;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class SearchController extends Controller
{
    private const MAX_RESULTS = 50;

    public function index(Request $request): mixed
    {
        $query      = trim($request->get('q', ''));
        $fromFilter = trim($request->get('from', ''));
        $since      = trim($request->get('since', ''));
        $before     = trim($request->get('before', ''));
        $folder     = trim($request->get('folder', 'INBOX'));
        $seen       = $request->get('seen', '');   // '' | '1' | '0'
        $hasAttach  = (bool) $request->get('attachment', false);

        $messages   = [];
        $folders    = [];
        $error      = null;
        $total      = 0;
        $hasFilters = $query !== '' || $fromFilter !== '' || $since !== '' || $before !== '' || $seen !== '' || $hasAttach;

        /** @var ImapGuard $guard */
        $guard    = auth('web');
        $imap     = new ImapConnection();

        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());

            $folders = MailboxListCache::get($guard->getImapLogin(), fn () => array_map(
                fn (array $f) => array_merge($f, $imap->getFolderStatus($f['name'])),
                $imap->listFolders()
            ));

            if ($hasFilters) {
                $searchFolder = $folder !== '' ? $folder : 'INBOX';
                $imap->selectFolder($searchFolder);

                $criteria = $this->buildCriteria($query, $fromFilter, $since, $before, $seen, $hasAttach);
                $uids     = array_slice($imap->search($criteria), 0, self::MAX_RESULTS);
                $total    = count($uids);
                $messages = $imap->fetchHeadersByUids($uids);
                $messages = $this->formatDates($messages);
            }

            $imap->logout();

        } catch (\Throwable $e) {
            $imap->close();
            $error = $e->getMessage();
        }

        return view(mailView('search.index'), [
            'folders'       => $folders,
            'currentFolder' => '',
            'query'         => $query,
            'fromFilter'    => $fromFilter,
            'since'         => $since,
            'before'        => $before,
            'searchFolder'  => $folder,
            'seen'          => $seen,
            'hasAttach'     => $hasAttach,
            'messages'      => $messages,
            'total'         => $total,
            'error'         => $error,
        ]);
    }

    // ------------------------------------------------------------------

    private function buildCriteria(string $q, string $from, string $since, string $before, string $seen, bool $hasAttach): string
    {
        $parts = [];

        if ($q !== '') {
            $escaped = '"' . addcslashes($q, '"\\') . '"';
            $parts[] = "OR SUBJECT {$escaped} FROM {$escaped}";
        }

        if ($from !== '') {
            $escaped = '"' . addcslashes($from, '"\\') . '"';
            $parts[] = "FROM {$escaped}";
        }

        if ($since !== '') {
            try {
                $dt      = Carbon::parse($since);
                $parts[] = 'SINCE ' . $dt->format('d-M-Y');
            } catch (\Throwable) {}
        }

        if ($before !== '') {
            try {
                $dt      = Carbon::parse($before);
                $parts[] = 'BEFORE ' . $dt->format('d-M-Y');
            } catch (\Throwable) {}
        }

        if ($seen === '1') {
            $parts[] = 'SEEN';
        } elseif ($seen === '0') {
            $parts[] = 'UNSEEN';
        }

        // Attachment detection: match multipart/mixed in Content-Type header
        if ($hasAttach) {
            $parts[] = 'HEADER Content-Type "multipart/mixed"';
        }

        return $parts === [] ? 'ALL' : implode(' ', $parts);
    }

    // ------------------------------------------------------------------

    private function formatDates(array $messages): array
    {
        $now = Carbon::now();

        return array_map(function (array $msg) use ($now): array {
            try {
                $dt = Carbon::parse($msg['date_raw']);
                $msg['date_formatted'] = $dt->isToday()
                    ? $dt->format('g:i A')
                    : ($dt->isSameYear($now) ? $dt->format('M j') : $dt->format('M j, Y'));
            } catch (\Throwable) {
                $msg['date_formatted'] = $msg['date_raw'];
            }
            return $msg;
        }, $messages);
    }
}
