<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When aimited version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapGuard;
use App\Models\UserSetting;
use App\Services\ImapConnection;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function index(): mixed
    {
        /** @var ImapGuard $guard */
        $guard = auth('web');
        $quota = null;

        try {
            $imap = new ImapConnection();
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 5),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $quota = $imap->getQuota();
            $imap->logout();
        } catch (\Throwable) {
        }

        return view(mailView('settings.index'), [
            'settings'      => userSettings(),
            'folders'       => [],
            'currentFolder' => '',
            'quota'         => $quota,
        ]);
    }

    public function update(Request $request): mixed
    {
        $data = $request->validate([
            'display_name'   => ['nullable', 'string', 'max:255'],
            'signature'      => ['nullable', 'string', 'max:5000'],
            'per_page'       => ['required', 'integer', 'in:10,25,50,100'],
            'image_loading'  => ['required', 'string', 'in:ask,always,never'],
            'reply_behavior' => ['required', 'string', 'in:reply,reply_all'],
            'theme'          => ['required', 'string', 'in:light,dark'],
            'read_receipt'   => ['required', 'string', 'in:ask,always,never'],
        ]);

        // Checkboxes are absent from the form when unchecked
        $data['notifications_enabled'] = $request->boolean('notifications_enabled');

        UserSetting::updateOrCreate(
            ['email' => auth('web')->user()->email],
            $data,
        );

        return redirect()->route('settings')->with('success', 'Settings saved.');
    }
}
