<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Models\UserSetting;
use App\Services\ManageSieveConnection;
use Illuminate\Http\Request;

class SieveController extends Controller
{
    private const SCRIPT_NAME = 'opterius';

    public function index(): mixed
    {
        abort_unless(config('mail.sieve_enabled', false), 404);

        $rules = $this->loadRules();

        return view(mailView('sieve.index'), [
            'rules'         => $rules,
            'folders'       => [],
            'currentFolder' => '',
        ]);
    }

    public function store(Request $request): mixed
    {
        abort_unless(config('mail.sieve_enabled', false), 404);

        $data = $request->validate([
            'condition'   => ['required', 'string', 'in:from,subject,to,all'],
            'value'       => ['required_unless:condition,all', 'nullable', 'string', 'max:255'],
            'action'      => ['required', 'string', 'in:move,delete,mark_read,flag'],
            'action_target' => ['nullable', 'string', 'max:255'],
        ]);

        $rules   = $this->loadRules();
        $rules[] = [
            'id'            => uniqid('rule_'),
            'condition'     => $data['condition'],
            'value'         => $data['value'] ?? '',
            'action'        => $data['action'],
            'action_target' => $data['action_target'] ?? '',
        ];

        $this->saveRules($rules);
        $this->pushToSieve($rules, $request);

        return redirect()->route('sieve.index')->with('success', 'Rule added.');
    }

    public function destroy(Request $request, string $id): mixed
    {
        abort_unless(config('mail.sieve_enabled', false), 404);

        $rules = array_values(array_filter(
            $this->loadRules(),
            fn($r) => $r['id'] !== $id,
        ));

        $this->saveRules($rules);
        $this->pushToSieve($rules, $request);

        return redirect()->route('sieve.index')->with('success', 'Rule deleted.');
    }

    // ------------------------------------------------------------------

    private function loadRules(): array
    {
        $email    = auth('web')->user()->email;
        $setting  = UserSetting::where('email', $email)->first();
        $raw      = $setting?->sieve_rules ?? '';
        $decoded  = $raw !== '' ? json_decode($raw, true) : null;
        return is_array($decoded) ? $decoded : [];
    }

    private function saveRules(array $rules): void
    {
        $email = auth('web')->user()->email;
        UserSetting::updateOrCreate(
            ['email' => $email],
            ['sieve_rules' => json_encode($rules)],
        );
    }

    private function pushToSieve(array $rules, Request $request): void
    {
        $host = config('imap.host');
        $port = (int) config('mail.sieve_port', 4190);

        /** @var \App\Auth\ImapGuard $guard */
        $guard    = auth('web');
        $username = $guard->getImapLogin();
        $password = $guard->getImapPassword();

        if (!$username || !$password) {
            return;
        }

        try {
            $conn = new ManageSieveConnection();
            $conn->connect($host, $port);
            $conn->login($username, $password);
            $conn->putScript(self::SCRIPT_NAME, $this->buildSieve($rules));
            $conn->setActive(self::SCRIPT_NAME);
            $conn->logout();
        } catch (\Throwable $e) {
            // Sieve errors are non-fatal — rules are still saved locally
            session()->flash('sieve_error', 'Rules saved but could not sync to server: ' . $e->getMessage());
        }
    }

    /**
     * Build a Sieve script from the rules array.
     */
    private function buildSieve(array $rules): string
    {
        if ($rules === []) {
            return "# Opterius Mail — no rules\r\n";
        }

        $extensions = ['fileinto'];
        $needsImap  = false;

        foreach ($rules as $r) {
            if ($r['action'] === 'mark_read' || $r['action'] === 'flag') {
                $extensions[] = 'imap4flags';
                $needsImap    = true;
                break;
            }
        }

        $requires = 'require [' . implode(', ', array_map(fn($e) => '"' . $e . '"', array_unique($extensions))) . "];\r\n\r\n";

        $body = '';
        foreach ($rules as $r) {
            $test   = $this->sieveTest($r);
            $action = $this->sieveAction($r);
            if ($test === null || $action === null) {
                continue;
            }
            $body .= "if {$test} {\r\n    {$action}\r\n}\r\n";
        }

        return $requires . $body;
    }

    private function sieveTest(array $rule): ?string
    {
        $val = addcslashes($rule['value'] ?? '', '"\\');
        return match ($rule['condition']) {
            'from'    => "header :contains \"From\" \"{$val}\"",
            'subject' => "header :contains \"Subject\" \"{$val}\"",
            'to'      => "header :contains \"To\" \"{$val}\"",
            'all'     => 'true',
            default   => null,
        };
    }

    private function sieveAction(array $rule): ?string
    {
        $target = addcslashes($rule['action_target'] ?? '', '"\\');
        return match ($rule['action']) {
            'move'      => "fileinto \"{$target}\";",
            'delete'    => 'discard;',
            'mark_read' => 'addflag "\\\\Seen";',
            'flag'      => 'addflag "\\\\Flagged";',
            default     => null,
        };
    }
}
