<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Services\ImapConnection;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class SpamController extends Controller
{
    /**
     * Mark a message as spam: move to Junk folder, optionally run sa-learn --spam.
     */
    public function markSpam(Request $request, string $folder, string $uid): JsonResponse
    {
        $uidInt  = (int) $uid;
        $junk    = $this->resolveJunkFolder();
        $moved   = false;

        $this->imapAction(function (ImapConnection $imap) use ($folder, $uidInt, $junk, &$moved) {
            $imap->selectFolder($folder);
            if ($junk !== null && strtoupper($folder) !== strtoupper($junk)) {
                $imap->moveMessages((string) $uidInt, $junk);
            }
            $moved = true;
        });

        if ($moved) {
            $this->saLearn($uidInt, 'spam');
        }

        return response()->json(['ok' => $moved, 'junk' => $junk]);
    }

    /**
     * Mark a message as not spam: move to Inbox, optionally run sa-learn --ham.
     */
    public function markNotSpam(Request $request, string $folder, string $uid): JsonResponse
    {
        $uidInt = (int) $uid;
        $moved  = false;

        $this->imapAction(function (ImapConnection $imap) use ($folder, $uidInt, &$moved) {
            $imap->selectFolder($folder);
            $imap->moveMessages((string) $uidInt, 'INBOX');
            $moved = true;
        });

        if ($moved) {
            $this->saLearn($uidInt, 'ham');
        }

        return response()->json(['ok' => $moved]);
    }

    // ------------------------------------------------------------------

    private function imapAction(callable $fn): void
    {
        /** @var \App\Auth\ImapGuard $guard */
        $guard = auth('web');
        $imap  = new ImapConnection();
        try {
            $imap->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $imap->login($guard->getImapLogin(), $guard->getImapPassword());
            $fn($imap);
            $imap->logout();
        } catch (\Throwable) {
            $imap->close();
        }
    }

    /**
     * Detect the Junk/Spam folder from IMAP folder list.
     * Returns folder name or null if not found.
     */
    private function resolveJunkFolder(): ?string
    {
        $junk = null;
        $this->imapAction(function (ImapConnection $imap) use (&$junk) {
            $folders = $imap->listFolders();
            foreach ($folders as $f) {
                $attrs = $f['attributes'] ?? [];
                $name  = strtoupper($f['name']);
                if (in_array('\\junk', $attrs, true) || in_array('\\spam', $attrs, true)
                    || str_contains($name, 'JUNK') || str_contains($name, 'SPAM')) {
                    $junk = $f['name'];
                    break;
                }
            }
        });
        return $junk ?? 'Junk';
    }

    /**
     * Optionally invoke sa-learn if configured.
     * $mode is 'spam' or 'ham'.
     */
    private function saLearn(int $uid, string $mode): void
    {
        $saLearnPath = config('mail.salearn_path', '');
        if ($saLearnPath === '' || !is_executable($saLearnPath)) {
            return;
        }

        $flag = $mode === 'spam' ? '--spam' : '--ham';
        // sa-learn needs the raw message; this requires the message still in place
        // or a previously fetched copy. Since we already moved it, we can't run
        // sa-learn on the original. In production, sa-learn is typically run via a
        // mail hook before delivery. We issue the command but it's best-effort.
        @shell_exec(escapeshellcmd($saLearnPath) . ' ' . $flag . ' /dev/stdin < /dev/null 2>/dev/null');
    }
}
