<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Auth\ImapUser;
use App\Services\ImapConnection;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Str;

/**
 * Panel SSO — token-based auto-login.
 *
 * Flow:
 *   1. Panel calls POST /sso/issue (server-to-server) with a signed request.
 *      Webmail validates the HMAC and returns a short-lived one-time token + URL.
 *   2. Panel redirects the user's browser to GET /sso/login?token={token}.
 *      Webmail validates the token, opens an IMAP session via Dovecot master user,
 *      and logs the user in.
 *
 * Required env vars:
 *   PANEL_SSO_ENABLED=true
 *   PANEL_SSO_SECRET={shared secret, min 32 chars}
 *   IMAP_MASTER_USER={dovecot master username}
 *   IMAP_MASTER_PASS={dovecot master password}
 */
class SsoController extends Controller
{
    private const TOKEN_TTL_SECONDS = 120;

    // ------------------------------------------------------------------
    // Step 1 — Panel issues a token (server-to-server)
    // ------------------------------------------------------------------

    /**
     * POST /sso/issue
     *
     * Expected JSON body:
     * {
     *   "email":     "user@example.com",
     *   "timestamp": 1713000000,          // Unix timestamp, must be within 60 s of server time
     *   "signature": "hex-hmac-sha256"    // HMAC-SHA256(secret, "{email}:{timestamp}")
     * }
     *
     * Returns:
     * { "token": "hex32", "url": "https://mail.example.com/sso/login?token=hex32" }
     */
    public function issue(Request $request): JsonResponse
    {
        if (!$this->ssoEnabled()) {
            return response()->json(['error' => 'SSO is disabled.'], 403);
        }

        $request->validate([
            'email'     => ['required', 'email'],
            'timestamp' => ['required', 'integer'],
            'signature' => ['required', 'string'],
        ]);

        $email     = strtolower($request->email);
        $timestamp = (int) $request->timestamp;
        $signature = $request->signature;

        // Reject requests outside a 60-second window (prevents replay)
        if (abs(time() - $timestamp) > 60) {
            return response()->json(['error' => 'Timestamp expired.'], 422);
        }

        // Verify HMAC
        $expected = hash_hmac('sha256', "{$email}:{$timestamp}", config('mail-ui.sso_secret'));
        if (!hash_equals($expected, strtolower($signature))) {
            return response()->json(['error' => 'Invalid signature.'], 403);
        }

        // Generate one-time token, store in cache for TOKEN_TTL_SECONDS
        $token = Str::random(48);
        Cache::put("sso:{$token}", $email, self::TOKEN_TTL_SECONDS);

        $url = url('/sso/login') . '?token=' . $token;

        return response()->json(['token' => $token, 'url' => $url]);
    }

    // ------------------------------------------------------------------
    // Step 2 — User browser arrives with the token
    // ------------------------------------------------------------------

    /**
     * GET /sso/login?token={token}
     */
    public function login(Request $request): mixed
    {
        if (!$this->ssoEnabled()) {
            return redirect()->route('login')->withErrors(['email' => 'SSO is disabled.']);
        }

        $token = $request->query('token', '');

        if (!$token) {
            return redirect()->route('login');
        }

        $cacheKey = "sso:{$token}";
        $email    = Cache::get($cacheKey);

        if (!$email) {
            return redirect()->route('login')
                ->withErrors(['email' => 'SSO token is invalid or has expired. Please try again.']);
        }

        // Consume the token immediately — single-use
        Cache::forget($cacheKey);

        $masterUser = config('imap.master_user');
        $masterPass = config('imap.master_pass');

        if (!$masterUser || !$masterPass) {
            return redirect()->route('login')
                ->withErrors(['email' => 'SSO is not fully configured on this server (missing master credentials).']);
        }

        // Authenticate via Dovecot master user: login as "{email}*{masterUser}"
        $imapLogin = "{$email}*{$masterUser}";

        $conn = new ImapConnection();
        try {
            $conn->connect(
                host:         config('imap.host'),
                port:         config('imap.port'),
                encryption:   config('imap.encryption'),
                validateCert: config('imap.validate_cert', false),
                timeout:      config('imap.timeout', 10),
            );
            $ok = $conn->login($imapLogin, $masterPass);
            $conn->logout();
        } catch (\Throwable) {
            $ok = false;
        }

        if (!$ok) {
            return redirect()->route('login')
                ->withErrors(['email' => 'SSO login failed — could not authenticate with mail server.']);
        }

        // CRITICAL: wipe any prior user's session before establishing the new
        // SSO session. Without flush(), `regenerate()` keeps all old data and
        // only the keys we explicitly set get overwritten — leaving stale
        // imap_login/imap_display_name/2fa_pending/userSettings cache from
        // the previous user, which can surface the wrong mailbox.
        session()->flush();
        session()->regenerate(true); // destroy old session ID

        session([
            'imap_email'        => $email,
            'imap_password'     => encrypt($masterPass),
            'imap_login'        => $imapLogin,
            'imap_display_name' => $email,
        ]);

        // Force the session to be persisted now, before the redirect, so the
        // next request reads the new data even with database/redis drivers.
        session()->save();

        // Hydrate the guard's in-memory user (only affects current request)
        $guard = auth('web');
        if (method_exists($guard, 'setUser')) {
            $guard->setUser(new ImapUser(email: $email, name: $email));
        }

        return redirect()->route('inbox');
    }

    // ------------------------------------------------------------------

    private function ssoEnabled(): bool
    {
        return config('mail-ui.sso_enabled') && !empty(config('mail-ui.sso_secret'));
    }
}
