<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers;

use App\Models\UserTwoFactor;
use App\Services\TotpService;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class TwoFactorController extends Controller
{
    /**
     * Show 2FA setup page (or management page if already enabled).
     */
    public function show(): mixed
    {
        $email  = auth('web')->user()->email;
        $record = UserTwoFactor::where('email', $email)->first();
        $totp   = new TotpService();

        if ($record && $record->isEnabled()) {
            return view(mailView('settings.2fa'), [
                'enabled'        => true,
                'recoveryCodes'  => $record->getRecoveryCodesArray(),
                'folders'        => [],
                'currentFolder'  => '',
            ]);
        }

        // Generate a new (or reuse pending) secret
        if (!$record) {
            $secret = $totp->generateSecret();
            $record = UserTwoFactor::create([
                'email'          => $email,
                'secret'         => encrypt($secret),
                'recovery_codes' => null,
                'enabled_at'     => null,
            ]);
        } else {
            $secret = decrypt($record->secret);
        }

        $qrUri = $totp->getQrUri($email, $secret);

        return view(mailView('settings.2fa'), [
            'enabled'       => false,
            'secret'        => $secret,
            'qrUri'         => $qrUri,
            'folders'       => [],
            'currentFolder' => '',
        ]);
    }

    /**
     * Confirm and enable 2FA.
     * POST /settings/2fa/enable  { code: "123456" }
     */
    public function enable(Request $request): mixed
    {
        $request->validate(['code' => ['required', 'string', 'digits:6']]);

        $email  = auth('web')->user()->email;
        $record = UserTwoFactor::where('email', $email)->first();

        if (!$record) {
            return back()->withErrors(['code' => 'Setup not initiated. Reload the page.']);
        }

        $secret = decrypt($record->secret);
        $totp   = new TotpService();

        if (!$totp->verify($secret, $request->input('code'))) {
            return back()->withErrors(['code' => 'Invalid code. Check your authenticator app and try again.']);
        }

        $codes = $totp->generateRecoveryCodes();

        $record->update([
            'recovery_codes' => json_encode($codes),
            'enabled_at'     => Carbon::now(),
        ]);

        return redirect()->route('2fa.setup')
            ->with('2fa_enabled', true)
            ->with('recovery_codes_fresh', $codes);
    }

    /**
     * Disable 2FA.
     * POST /settings/2fa/disable  { code: "123456" }
     */
    public function disable(Request $request): mixed
    {
        $request->validate(['code' => ['required', 'string']]);

        $email  = auth('web')->user()->email;
        $record = UserTwoFactor::where('email', $email)->first();

        if (!$record || !$record->isEnabled()) {
            return redirect()->route('settings');
        }

        $secret = decrypt($record->secret);
        $totp   = new TotpService();

        // Accept either a TOTP code or a recovery code
        $valid = $totp->verify($secret, $request->input('code'))
            || $this->consumeRecoveryCode($record, $request->input('code'));

        if (!$valid) {
            return back()->withErrors(['code' => 'Invalid code.']);
        }

        $record->delete();

        return redirect()->route('settings')->with('success', 'Two-factor authentication disabled.');
    }

    // ------------------------------------------------------------------

    private function consumeRecoveryCode(UserTwoFactor $record, string $code): bool
    {
        $codes = $record->getRecoveryCodesArray();
        $clean = strtoupper(str_replace('-', '', preg_replace('/\s+/', '', $code)));

        foreach ($codes as $i => $stored) {
            if (strtoupper(str_replace('-', '', $stored)) === $clean) {
                unset($codes[$i]);
                $record->update(['recovery_codes' => json_encode(array_values($codes))]);
                return true;
            }
        }

        return false;
    }
}
