<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AdminSetting extends Model
{
    public $incrementing = false;
    public $timestamps   = false;

    protected $table      = 'admin_settings';
    protected $primaryKey = 'key';
    protected $keyType    = 'string';

    protected $fillable = ['key', 'value'];

    // Default values for every key
    private const DEFAULTS = [
        'webmail_name'         => 'Opterius Mail',
        'default_hourly_limit' => null,
        'default_daily_limit'  => null,
        'default_weekly_limit' => null,
        'default_monthly_limit'=> null,
        'default_max_recipients' => null,
    ];

    /**
     * Get a setting value by key, returning the default when not set.
     */
    public static function get(string $key): mixed
    {
        $row = static::find($key);
        return $row ? $row->value : (self::DEFAULTS[$key] ?? null);
    }

    /**
     * Set (upsert) a setting value.
     */
    public static function set(string $key, mixed $value): void
    {
        static::updateOrCreate(['key' => $key], ['value' => $value]);
    }

    /**
     * Return all settings merged with defaults as a plain array.
     */
    public static function allSettings(): array
    {
        $stored = static::all()->pluck('value', 'key')->toArray();
        return array_merge(self::DEFAULTS, $stored);
    }
}
