<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Autoresponder extends Model
{
    protected $fillable = [
        'email',
        'subject',
        'body',
        'starts_at',
        'ends_at',
        'is_active',
    ];

    protected $casts = [
        'starts_at' => 'date',
        'ends_at'   => 'date',
        'is_active' => 'boolean',
    ];

    /**
     * Whether this autoresponder should fire right now.
     */
    public function isCurrentlyActive(): bool
    {
        if (!$this->is_active) {
            return false;
        }

        $today = Carbon::today();

        if ($this->starts_at && $today->lt($this->starts_at)) {
            return false;
        }

        if ($this->ends_at && $today->gt($this->ends_at)) {
            return false;
        }

        return true;
    }

    /**
     * Whether a response has already been sent to the given address.
     */
    public function alreadyRespondedTo(string $email): bool
    {
        return \DB::table('autoresponder_log')
            ->where('autoresponder_id', $this->id)
            ->where('to_email', strtolower($email))
            ->exists();
    }

    /**
     * Record that a response was sent to the given address.
     */
    public function markRespondedTo(string $email): void
    {
        \DB::table('autoresponder_log')->insertOrIgnore([
            'autoresponder_id' => $this->id,
            'to_email'         => strtolower($email),
            'created_at'       => now(),
        ]);
    }
}
