<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Contact extends Model
{
    protected $fillable = ['owner_email', 'name', 'email', 'phone', 'notes', 'avatar', 'birthday', 'website', 'address'];

    protected $casts = [
        'birthday' => 'date',
    ];

    public function groups(): BelongsToMany
    {
        return $this->belongsToMany(ContactGroup::class, 'contact_group_contact');
    }

    public function avatarUrl(): ?string
    {
        return $this->avatar ? asset('storage/contact-avatars/' . $this->avatar) : null;
    }

    public function initial(): string
    {
        return mb_strtoupper(mb_substr($this->name ?: $this->email, 0, 1, 'UTF-8'), 'UTF-8');
    }
}
