<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class ContactGroup extends Model
{
    protected $fillable = ['owner_email', 'name', 'color'];

    public const COLORS = [
        'gray'   => ['badge' => 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300',   'dot' => 'bg-gray-400'],
        'red'    => ['badge' => 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',     'dot' => 'bg-red-400'],
        'orange' => ['badge' => 'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300', 'dot' => 'bg-orange-400'],
        'yellow' => ['badge' => 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/40 dark:text-yellow-300', 'dot' => 'bg-yellow-400'],
        'green'  => ['badge' => 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300',  'dot' => 'bg-green-400'],
        'blue'   => ['badge' => 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',   'dot' => 'bg-blue-400'],
        'purple' => ['badge' => 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300', 'dot' => 'bg-purple-400'],
        'pink'   => ['badge' => 'bg-pink-100 text-pink-700 dark:bg-pink-900/40 dark:text-pink-300',   'dot' => 'bg-pink-400'],
    ];

    public function contacts(): BelongsToMany
    {
        return $this->belongsToMany(Contact::class, 'contact_group_contact');
    }

    public function badgeClass(): string
    {
        return self::COLORS[$this->color]['badge'] ?? self::COLORS['gray']['badge'];
    }

    public function dotClass(): string
    {
        return self::COLORS[$this->color]['dot'] ?? self::COLORS['gray']['dot'];
    }
}
