<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DkimKey extends Model
{
    protected $table = 'dkim_keys';

    protected $fillable = [
        'domain',
        'selector',
        'private_key',
        'public_key',
        'dns_record',
    ];

    /**
     * Generate a new 2048-bit RSA DKIM keypair and return a new (unsaved) instance.
     *
     * @throws \RuntimeException if OpenSSL is unavailable or key generation fails
     */
    public static function generate(string $domain, string $selector = 'mail'): static
    {
        $resource = openssl_pkey_new([
            'private_key_bits' => 2048,
            'private_key_type' => OPENSSL_KEYTYPE_RSA,
        ]);

        if ($resource === false) {
            throw new \RuntimeException('OpenSSL key generation failed: ' . openssl_error_string());
        }

        openssl_pkey_export($resource, $privateKey);
        $details   = openssl_pkey_get_details($resource);
        $publicPem = $details['key'];

        // Strip PEM headers and whitespace to get the bare base64 for the DNS record
        $publicB64 = preg_replace('/-----[^-]+-----|[\r\n\s]/', '', $publicPem);
        $dnsRecord = "v=DKIM1; k=rsa; p={$publicB64}";

        return new static([
            'domain'      => strtolower(trim($domain)),
            'selector'    => strtolower(trim($selector)) ?: 'mail',
            'private_key' => $privateKey,
            'public_key'  => $publicPem,
            'dns_record'  => $dnsRecord,
        ]);
    }

    /**
     * The DNS name for this key (e.g. mail._domainkey.example.com).
     */
    public function dnsName(): string
    {
        return "{$this->selector}._domainkey.{$this->domain}";
    }
}
