<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class MailSendLog extends Model
{
    public $timestamps = false;

    protected $table = 'mail_send_log';

    protected $fillable = [
        'email',
        'recipient_count',
        'subject',
        'ip',
        'status',
        'created_at',
    ];

    protected $casts = [
        'created_at' => 'datetime',
    ];

    /**
     * Record a successful outbound send.
     */
    public static function record(
        string $email,
        int    $recipientCount,
        string $subject,
        string $ip     = '',
        string $status = 'sent',
    ): void {
        static::create([
            'email'           => $email,
            'recipient_count' => max(1, $recipientCount),
            'subject'         => mb_substr($subject, 0, 998),
            'ip'              => $ip ?: null,
            'status'          => $status,
            'created_at'      => now(),
        ]);
    }
}
