<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class MailGroup extends Model
{
    protected $table = 'mail_groups';

    protected $fillable = [
        'name',
        'description',
        'max_recipients',
        'hourly_limit',
        'daily_limit',
        'weekly_limit',
        'monthly_limit',
    ];

    protected $casts = [
        'max_recipients' => 'integer',
        'hourly_limit'   => 'integer',
        'daily_limit'    => 'integer',
        'weekly_limit'   => 'integer',
        'monthly_limit'  => 'integer',
    ];

    public function members(): HasMany
    {
        return $this->hasMany(UserSetting::class, 'group_id');
    }

    /**
     * Human-readable limit string for display (e.g. "100/day, 500/month").
     */
    public function limitsLabel(): string
    {
        $parts = [];
        if ($this->hourly_limit !== null)  $parts[] = "{$this->hourly_limit}/hr";
        if ($this->daily_limit !== null)   $parts[] = "{$this->daily_limit}/day";
        if ($this->weekly_limit !== null)  $parts[] = "{$this->weekly_limit}/wk";
        if ($this->monthly_limit !== null) $parts[] = "{$this->monthly_limit}/mo";
        return $parts ? implode(', ', $parts) : 'Unlimited';
    }
}
