<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserSetting extends Model
{
    protected $table = 'user_settings';

    protected $fillable = [
        'email',
        'group_id',
        'display_name',
        'signature',
        'per_page',
        'image_loading',
        'reply_behavior',
        'theme',
        'template',
        'sieve_rules',
        'notifications_enabled',
        'read_receipt',
    ];

    protected $casts = [
        'per_page'              => 'integer',
        'notifications_enabled' => 'boolean',
    ];

    /** Default values used when no row exists yet. */
    public static function defaults(): array
    {
        return [
            'display_name'          => '',
            'signature'             => '',
            'per_page'              => 25,
            'image_loading'         => 'ask',
            'reply_behavior'        => 'reply',
            'theme'                 => 'light',
            'template'              => null,
            'notifications_enabled' => true,
            'read_receipt'          => 'ask',
        ];
    }
}
