<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserTwoFactor extends Model
{
    protected $table    = 'user_two_factor';
    protected $fillable = ['email', 'secret', 'recovery_codes', 'enabled_at'];
    protected $casts    = ['enabled_at' => 'datetime'];

    public function isEnabled(): bool
    {
        return $this->enabled_at !== null;
    }

    /** Return recovery codes as an array. */
    public function getRecoveryCodesArray(): array
    {
        if ($this->recovery_codes === null || $this->recovery_codes === '') {
            return [];
        }
        $decoded = json_decode($this->recovery_codes, true);
        return is_array($decoded) ? $decoded : [];
    }
}
