<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\MailAccount;
use App\Models\MailDomain;
use App\Models\MailGroup;
use Illuminate\Http\Request;
use Illuminate\Validation\Rules\Password;

class AccountController extends Controller
{
    public function index(Request $request)
    {
        $standaloneMode = !config('mail-ui.admin_mode');

        if ($standaloneMode) {
            $query = \App\Models\UserSetting::with('group')->orderBy('email');
            if ($request->filled('search')) {
                $query->where('email', 'like', '%' . $request->search . '%');
            }
            $accounts = $query->paginate(50)->withQueryString();
            $domains  = collect();
            return view(mailView('admin.accounts.index'), compact('accounts', 'domains', 'standaloneMode'));
        }

        $query = MailAccount::with(['domain', 'group'])->orderBy('email');
        if ($request->filled('domain')) {
            $query->whereHas('domain', fn($q) => $q->where('domain', $request->domain));
        }
        $accounts       = $query->paginate(50)->withQueryString();
        $domains        = MailDomain::orderBy('domain')->pluck('domain');
        $standaloneMode = false;

        return view(mailView('admin.accounts.index'), compact('accounts', 'domains', 'standaloneMode'));
    }

    public function create()
    {
        $domains = MailDomain::where('is_active', true)->orderBy('domain')->get();
        $groups  = MailGroup::orderBy('name')->get();

        return view(mailView('admin.accounts.create'), compact('domains', 'groups'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'domain_id' => ['required', 'exists:mail_domains,id'],
            'local'     => ['required', 'string', 'max:64', 'regex:/^[a-zA-Z0-9._%+\-]+$/'],
            'password'  => ['required', 'confirmed', Password::min(8)],
            'quota_mb'  => ['nullable', 'integer', 'min:1', 'max:1048576'],
            'group_id'  => ['nullable', 'exists:mail_groups,id'],
        ]);

        $domain = MailDomain::findOrFail($request->domain_id);
        $email  = strtolower($request->local) . '@' . $domain->domain;

        if (MailAccount::where('email', $email)->exists()) {
            return back()->withInput()->withErrors(['local' => "Account {$email} already exists."]);
        }

        MailAccount::create([
            'domain_id' => $request->domain_id,
            'email'     => $email,
            'password'  => $request->password,
            'quota_mb'  => $request->quota_mb ?: null,
            'is_active' => true,
            'group_id'  => $request->group_id ?: null,
        ]);

        return redirect()->route('admin.accounts.index')
            ->with('success', "Account {$email} created.");
    }

    public function edit(MailAccount $mail_account)
    {
        $mail_account->load(['domain', 'group']);
        $groups = MailGroup::orderBy('name')->get();

        return view(mailView('admin.accounts.edit'), compact('mail_account', 'groups'));
    }

    public function update(Request $request, MailAccount $mail_account)
    {
        $request->validate([
            'password' => ['nullable', 'confirmed', Password::min(8)],
            'quota_mb' => ['nullable', 'integer', 'min:1', 'max:1048576'],
            'group_id' => ['nullable', 'exists:mail_groups,id'],
        ]);

        $data = [
            'quota_mb' => $request->quota_mb ?: null,
            'group_id' => $request->group_id ?: null,
        ];

        if ($request->filled('password')) {
            $data['password'] = $request->password;
        }

        $mail_account->update($data);

        return redirect()->route('admin.accounts.index')
            ->with('success', "Account {$mail_account->email} updated.");
    }

    public function toggle(MailAccount $mail_account)
    {
        $mail_account->update(['is_active' => !$mail_account->is_active]);

        $state = $mail_account->is_active ? 'enabled' : 'suspended';

        return redirect()->route('admin.accounts.index')
            ->with('success', "Account {$mail_account->email} {$state}.");
    }

    public function destroy(MailAccount $mail_account)
    {
        $email = $mail_account->email;
        $mail_account->delete();

        return redirect()->route('admin.accounts.index')
            ->with('success', "Account {$email} deleted.");
    }
}
