<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\MailAlias;
use App\Models\MailDomain;
use Illuminate\Http\Request;

class AliasController extends Controller
{
    public function index(Request $request)
    {
        $query = MailAlias::with('domain')->orderBy('alias_email');

        if ($request->filled('domain')) {
            $query->whereHas('domain', fn($q) => $q->where('domain', $request->domain));
        }

        $aliases = $query->paginate(50)->withQueryString();
        $domains = MailDomain::orderBy('domain')->pluck('domain');

        return view(mailView('admin.aliases.index'), compact('aliases', 'domains'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'domain_id'         => ['required', 'exists:mail_domains,id'],
            'local'             => ['required', 'string', 'max:64', 'regex:/^[a-zA-Z0-9._%+\-]+$/'],
            'destination_email' => ['required', 'email', 'max:255'],
        ]);

        $domain = MailDomain::findOrFail($request->domain_id);
        $alias  = strtolower($request->local) . '@' . $domain->domain;

        if (MailAlias::where('alias_email', $alias)->exists()) {
            return back()->withInput()->withErrors(['local' => "Alias {$alias} already exists."]);
        }

        MailAlias::create([
            'domain_id'         => $request->domain_id,
            'alias_email'       => $alias,
            'destination_email' => strtolower($request->destination_email),
            'is_active'         => true,
        ]);

        return redirect()->route('admin.aliases.index')
            ->with('success', "Alias {$alias} → {$request->destination_email} created.");
    }

    public function update(Request $request, MailAlias $mail_alias)
    {
        $request->validate([
            'destination_email' => ['required', 'email', 'max:255'],
        ]);

        $mail_alias->update(['destination_email' => strtolower($request->destination_email)]);

        return redirect()->route('admin.aliases.index')
            ->with('success', "Alias {$mail_alias->alias_email} updated.");
    }

    public function toggle(MailAlias $mail_alias)
    {
        $mail_alias->update(['is_active' => !$mail_alias->is_active]);

        $state = $mail_alias->is_active ? 'enabled' : 'disabled';

        return redirect()->route('admin.aliases.index')
            ->with('success', "Alias {$mail_alias->alias_email} {$state}.");
    }

    public function destroy(MailAlias $mail_alias)
    {
        $alias = $mail_alias->alias_email;
        $mail_alias->delete();

        return redirect()->route('admin.aliases.index')
            ->with('success', "Alias {$alias} deleted.");
    }
}
