<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel / Opterius
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Chimilevschi Iosif-Gabriel / Opterius
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Chimilevschi Iosif-Gabriel <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    // ------------------------------------------------------------------
    // Setup — first admin (runs only when admins table is empty)
    // ------------------------------------------------------------------

    public function showSetup()
    {
        if (Admin::count() > 0) {
            abort(404);
        }
        return view(mailView('admin.auth.setup'));
    }

    public function setup(Request $request)
    {
        if (Admin::count() > 0) {
            abort(404);
        }

        $data = $request->validate([
            'name'                  => ['required', 'string', 'max:100'],
            'username'              => ['required', 'string', 'max:50', 'alpha_dash'],
            'password'              => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        $admin = Admin::create($data);

        Auth::guard('admin')->login($admin);

        return redirect()->route('admin.dashboard');
    }

    // ------------------------------------------------------------------
    // Login
    // ------------------------------------------------------------------

    public function showLogin()
    {
        if (Auth::guard('admin')->check()) {
            return redirect()->route('admin.dashboard');
        }
        return view(mailView('admin.auth.login'));
    }

    public function login(Request $request)
    {
        $credentials = $request->validate([
            'username' => ['required', 'string'],
            'password' => ['required', 'string'],
        ]);

        if (!Auth::guard('admin')->attempt($credentials, $request->boolean('remember'))) {
            return back()
                ->withInput($request->only('username'))
                ->withErrors(['username' => 'Invalid username or password.']);
        }

        $request->session()->regenerate();

        return redirect()->route('admin.dashboard');
    }

    public function logout(Request $request)
    {
        Auth::guard('admin')->logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();
        return redirect()->route('admin.login');
    }

    // ------------------------------------------------------------------
    // 2FA (placeholder — implemented when 2FA feature is built)
    // ------------------------------------------------------------------

    public function show2fa()
    {
        return view(mailView('admin.auth.2fa'));
    }

    public function verify2fa(Request $request)
    {
        return redirect()->route('admin.dashboard');
    }
}
