<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\LoginLog;
use App\Models\MailGroup;
use App\Models\MailSendLog;
use Illuminate\Support\Carbon;

class DashboardController extends Controller
{
    public function index()
    {
        $today     = Carbon::today();
        $weekStart = Carbon::now()->startOfWeek();
        $monthStart= Carbon::now()->startOfMonth();

        // Send stats
        $sentToday  = MailSendLog::whereDate('created_at', $today)->where('status', 'sent')->count();
        $sentWeek   = MailSendLog::where('created_at', '>=', $weekStart)->where('status', 'sent')->count();
        $sentMonth  = MailSendLog::where('created_at', '>=', $monthStart)->where('status', 'sent')->count();
        $failedToday= MailSendLog::whereDate('created_at', $today)->where('status', 'failed')->count();

        // Active users: distinct senders in the last 30 days
        $activeUsers = MailSendLog::where('created_at', '>=', Carbon::now()->subDays(30))
            ->distinct('email')
            ->count('email');

        // Login stats
        $loginsToday = LoginLog::whereDate('created_at', $today)->where('success', true)->count();
        $failedLogins= LoginLog::whereDate('created_at', $today)->where('success', false)->count();

        // Recent activity
        $recentSends  = MailSendLog::orderByDesc('created_at')->limit(15)->get();
        $recentLogins = LoginLog::orderByDesc('created_at')->limit(15)->get();

        // Groups count
        $groupCount = MailGroup::count();

        return view(mailView('admin.dashboard.index'), compact(
            'sentToday', 'sentWeek', 'sentMonth', 'failedToday',
            'activeUsers', 'loginsToday', 'failedLogins',
            'recentSends', 'recentLogins', 'groupCount',
        ));
    }
}
