<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\DkimKey;
use Illuminate\Http\Request;

class DkimController extends Controller
{
    public function index()
    {
        $keys = DkimKey::orderBy('domain')->orderBy('selector')->get();
        return view(mailView('admin.dkim.index'), compact('keys'));
    }

    public function generate(Request $request, string $domain)
    {
        $data = $request->validate([
            'domain'   => ['required', 'string', 'max:255', 'regex:/^[a-z0-9.\-]+$/i'],
            'selector' => ['nullable', 'string', 'max:63', 'regex:/^[a-z0-9\-]+$/i'],
        ]);

        $domain   = strtolower(trim($data['domain']));
        $selector = strtolower(trim($data['selector'] ?? 'mail')) ?: 'mail';

        // Revoke existing key for this domain+selector if present
        DkimKey::where('domain', $domain)->where('selector', $selector)->delete();

        try {
            $key = DkimKey::generate($domain, $selector);
            $key->save();
        } catch (\RuntimeException $e) {
            return redirect()->route('admin.dkim.index')
                ->with('error', 'Key generation failed: ' . $e->getMessage());
        }

        return redirect()->route('admin.dkim.index')
            ->with('success', "DKIM key generated for {$domain} (selector: {$selector}).");
    }

    public function destroy(DkimKey $dkim_key)
    {
        $label = "{$dkim_key->selector}._domainkey.{$dkim_key->domain}";
        $dkim_key->delete();
        return redirect()->route('admin.dkim.index')
            ->with('success', "Key {$label} deleted.");
    }
}
