<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\DkimKey;
use App\Models\MailDomain;
use Illuminate\Http\Request;

class DomainController extends Controller
{
    public function index()
    {
        $domains = MailDomain::withCount(['accounts', 'aliases'])
            ->orderBy('domain')
            ->paginate(30);

        return view(mailView('admin.domains.index'), compact('domains'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'domain' => ['required', 'string', 'max:255', 'unique:mail_domains,domain'],
        ]);

        MailDomain::create([
            'domain'    => strtolower(trim($request->domain)),
            'is_active' => true,
        ]);

        return redirect()->route('admin.domains.index')
            ->with('success', "Domain {$request->domain} added.");
    }

    public function toggle(MailDomain $mail_domain)
    {
        $mail_domain->update(['is_active' => !$mail_domain->is_active]);

        $state = $mail_domain->is_active ? 'enabled' : 'disabled';

        return redirect()->route('admin.domains.index')
            ->with('success', "Domain {$mail_domain->domain} {$state}.");
    }

    public function destroy(MailDomain $mail_domain)
    {
        $domain = $mail_domain->domain;
        $mail_domain->delete();

        return redirect()->route('admin.domains.index')
            ->with('success', "Domain {$domain} and all its accounts/aliases deleted.");
    }

    public function dns(MailDomain $mail_domain)
    {
        $domain = $mail_domain->domain;

        $mx    = $this->checkMx($domain);
        $spf   = $this->checkSpf($domain);
        $dmarc = $this->checkDmarc($domain);
        $dkim  = $this->checkDkim($domain);

        return view(mailView('admin.domains.dns'), compact('mail_domain', 'mx', 'spf', 'dmarc', 'dkim'));
    }

    // ------------------------------------------------------------------
    // DNS helpers
    // ------------------------------------------------------------------

    private function checkMx(string $domain): array
    {
        $records = @dns_get_record($domain, DNS_MX) ?: [];

        return [
            'found'   => count($records) > 0,
            'records' => array_map(fn($r) => "Priority {$r['pri']}: {$r['target']}", $records),
        ];
    }

    private function checkSpf(string $domain): array
    {
        $records = @dns_get_record($domain, DNS_TXT) ?: [];
        $spf = null;

        foreach ($records as $r) {
            $txt = $r['txt'] ?? implode('', $r['entries'] ?? []);
            if (str_starts_with($txt, 'v=spf1')) {
                $spf = $txt;
                break;
            }
        }

        return [
            'found'  => $spf !== null,
            'record' => $spf,
        ];
    }

    private function checkDmarc(string $domain): array
    {
        $records = @dns_get_record("_dmarc.{$domain}", DNS_TXT) ?: [];
        $dmarc = null;

        foreach ($records as $r) {
            $txt = $r['txt'] ?? implode('', $r['entries'] ?? []);
            if (str_starts_with($txt, 'v=DMARC1')) {
                $dmarc = $txt;
                break;
            }
        }

        return [
            'found'  => $dmarc !== null,
            'record' => $dmarc,
        ];
    }

    private function checkDkim(string $domain): array
    {
        $keys = DkimKey::where('domain', $domain)->get();
        $results = [];

        foreach ($keys as $key) {
            $host = $key->dnsName();
            $records = @dns_get_record($host, DNS_TXT) ?: [];
            $published = false;

            foreach ($records as $r) {
                $txt = $r['txt'] ?? implode('', $r['entries'] ?? []);
                if (str_contains($txt, 'v=DKIM1')) {
                    $published = true;
                    break;
                }
            }

            $results[] = [
                'selector'  => $key->selector,
                'host'      => $host,
                'published' => $published,
            ];
        }

        return $results;
    }
}
