<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

class ExportController extends Controller
{
    public function index()
    {
        $db      = $this->dbConfig();
        $driver  = $db['driver'];
        $isMysql = in_array($driver, ['mysql', 'pgsql', 'mariadb'], true);

        // Config snippets only make sense for MySQL/MariaDB
        $dovecot = $isMysql ? $this->dovecotConfig($db) : null;
        $postfix = $isMysql ? $this->postfixConfig($db) : null;

        return view(mailView('admin.settings.export'), compact('db', 'isMysql', 'dovecot', 'postfix'));
    }

    // ------------------------------------------------------------------
    // Dovecot
    // ------------------------------------------------------------------

    private function dovecotConfig(array $db): array
    {
        $connect = "host={$db['host']} port={$db['port']} dbname={$db['database']} user={$db['username']} password={$db['password']}";

        $sqlConf = <<<CONF
        # /etc/dovecot/dovecot-sql.conf.ext
        # Generated by Opterius Mail admin panel.
        # Passwords are stored as bcrypt (BLF-CRYPT). Laravel's Hash::make() is compatible.

        driver  = mysql
        connect = {$connect}

        default_pass_scheme = BLF-CRYPT

        # Authenticate: look up the hashed password for this mailbox.
        password_query = \\
            SELECT password \\
            FROM   mail_accounts \\
            WHERE  email = '%u' \\
              AND  is_active = 1

        # User info: home directory, system uid/gid, and optional quota.
        # Adjust vmail uid/gid (1000) and mail root (/var/mail/vhosts) to match your system.
        user_query = \\
            SELECT CONCAT('/var/mail/vhosts/%d/%n') AS home, \\
                   1000 AS uid, \\
                   1000 AS gid, \\
                   IF(quota_mb IS NULL, NULL, CONCAT('*:bytes=', quota_mb * 1048576)) AS quota_rule \\
            FROM   mail_accounts \\
            WHERE  email = '%u' \\
              AND  is_active = 1

        # Allows 'doveadm user' and 'doveadm mailbox list' to enumerate all accounts.
        iterate_query = \\
            SELECT email AS username \\
            FROM   mail_accounts \\
            WHERE  is_active = 1
        CONF;

        $dovecotConf = <<<CONF
        # /etc/dovecot/conf.d/auth-sql.conf.ext  (or similar)
        # Add these passdb / userdb blocks to your Dovecot auth config.

        passdb {
          driver = sql
          args   = /etc/dovecot/dovecot-sql.conf.ext
        }

        userdb {
          driver = sql
          args   = /etc/dovecot/dovecot-sql.conf.ext
        }
        CONF;

        $mailConf = <<<CONF
        # /etc/dovecot/conf.d/10-mail.conf  (relevant lines)
        # Adjust the mail location to match your user_query home path above.

        mail_location = maildir:/var/mail/vhosts/%d/%n
        CONF;

        $quotaConf = <<<CONF
        # /etc/dovecot/conf.d/90-quota.conf  (relevant lines)
        # Enables per-user quota from the userdb quota_rule field.

        plugin {
          quota           = maildir:User quota
          quota_rule      = *:storage=0
          quota_grace     = 10%%
        }

        service quota-warning {
          executable = script /usr/local/bin/quota-warning.sh
          unix_listener quota-warning {
            user = vmail
          }
        }
        CONF;

        return compact('sqlConf', 'dovecotConf', 'mailConf', 'quotaConf');
    }

    // ------------------------------------------------------------------
    // Postfix
    // ------------------------------------------------------------------

    private function postfixConfig(array $db): array
    {
        $common = <<<CONF
        user     = {$db['username']}
        password = {$db['password']}
        hosts    = {$db['host']}
        dbname   = {$db['database']}
        CONF;

        $domains = <<<CONF
        # /etc/postfix/mysql_virtual_domains.cf
        {$common}
        query = SELECT domain FROM mail_domains WHERE domain='%s' AND is_active=1
        CONF;

        $mailboxes = <<<CONF
        # /etc/postfix/mysql_virtual_mailboxes.cf
        {$common}
        query = SELECT CONCAT('%d', '/', '%u', '/') FROM mail_accounts WHERE email='%s' AND is_active=1
        CONF;

        $aliases = <<<CONF
        # /etc/postfix/mysql_virtual_aliases.cf
        {$common}
        query = SELECT destination_email FROM mail_aliases WHERE alias_email='%s' AND is_active=1
        CONF;

        $mainCf = <<<CONF
        # /etc/postfix/main.cf  — add or merge these lines.
        # Adjust virtual_mailbox_base to match your Dovecot mail_location root.

        virtual_mailbox_domains = mysql:/etc/postfix/mysql_virtual_domains.cf
        virtual_mailbox_base    = /var/mail/vhosts
        virtual_mailbox_maps    = mysql:/etc/postfix/mysql_virtual_mailboxes.cf
        virtual_alias_maps      = mysql:/etc/postfix/mysql_virtual_aliases.cf
        virtual_minimum_uid     = 100
        virtual_uid_maps        = static:1000
        virtual_gid_maps        = static:1000
        CONF;

        return compact('domains', 'mailboxes', 'aliases', 'mainCf');
    }

    // ------------------------------------------------------------------

    private function dbConfig(): array
    {
        $conn = config('database.default');
        $cfg  = config("database.connections.{$conn}");

        return [
            'driver'   => $cfg['driver']   ?? $conn,
            'host'     => $cfg['host']     ?? '127.0.0.1',
            'port'     => $cfg['port']     ?? '3306',
            'database' => $cfg['database'] ?? '',
            'username' => $cfg['username'] ?? '',
            'password' => $cfg['password'] ?? '',
        ];
    }
}
