<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\MailGroup;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    public function index()
    {
        $groups = MailGroup::withCount('members')->orderBy('name')->get();
        return view(mailView('admin.groups.index'), compact('groups'));
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'name'            => ['required', 'string', 'max:100', 'unique:mail_groups,name'],
            'description'     => ['nullable', 'string', 'max:500'],
            'max_recipients'  => ['nullable', 'integer', 'min:1', 'max:9999'],
            'hourly_limit'    => ['nullable', 'integer', 'min:1'],
            'daily_limit'     => ['nullable', 'integer', 'min:1'],
            'weekly_limit'    => ['nullable', 'integer', 'min:1'],
            'monthly_limit'   => ['nullable', 'integer', 'min:1'],
        ]);

        MailGroup::create($data);

        return redirect()->route('admin.groups.index')->with('success', "Group \"{$data['name']}\" created.");
    }

    public function update(Request $request, MailGroup $mail_group)
    {
        $data = $request->validate([
            'name'            => ['required', 'string', 'max:100', "unique:mail_groups,name,{$mail_group->id}"],
            'description'     => ['nullable', 'string', 'max:500'],
            'max_recipients'  => ['nullable', 'integer', 'min:1', 'max:9999'],
            'hourly_limit'    => ['nullable', 'integer', 'min:1'],
            'daily_limit'     => ['nullable', 'integer', 'min:1'],
            'weekly_limit'    => ['nullable', 'integer', 'min:1'],
            'monthly_limit'   => ['nullable', 'integer', 'min:1'],
        ]);

        $mail_group->update($data);

        return redirect()->route('admin.groups.index')->with('success', "Group \"{$mail_group->name}\" updated.");
    }

    public function destroy(MailGroup $mail_group)
    {
        // Members will have group_id set to null via nullOnDelete FK
        $mail_group->delete();
        return redirect()->route('admin.groups.index')->with('success', 'Group deleted.');
    }
}
