<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\AdminSetting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function index()
    {
        $settings = AdminSetting::allSettings();
        return view(mailView('admin.settings.index'), compact('settings'));
    }

    public function update(Request $request)
    {
        $data = $request->validate([
            'webmail_name'           => ['nullable', 'string', 'max:100'],
            'default_hourly_limit'   => ['nullable', 'integer', 'min:1'],
            'default_daily_limit'    => ['nullable', 'integer', 'min:1'],
            'default_weekly_limit'   => ['nullable', 'integer', 'min:1'],
            'default_monthly_limit'  => ['nullable', 'integer', 'min:1'],
            'default_max_recipients' => ['nullable', 'integer', 'min:1', 'max:9999'],
        ]);

        foreach ($data as $key => $value) {
            AdminSetting::set($key, $value !== '' ? $value : null);
        }

        return redirect()->route('admin.settings.index')->with('success', 'Settings saved.');
    }
}
