<?php

/**
 * Opterius Mail - Open source webmail.
 * Modern, fast and responsive webmail that works with any IMAP/SMTP server.
 * https://opterius.com
 *
 * Copyright (c) Host Server SRL (Opterius)
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code
 * of licensed works and modifications, which include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 * When a modified version is used to provide a service over a network, the complete source code of the
 * modified version must be made available.
 *
 * @copyright    Copyright (c) Host Server SRL (Opterius)
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@opterius.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software update.
 *  For custom changes, use the template and plugin system.
 */

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\MailAccount;
use Illuminate\Http\Request;

class UsageController extends Controller
{
    public function index(Request $request): mixed
    {
        $sort  = $request->input('sort', 'email');
        $dir   = $request->input('dir', 'asc') === 'desc' ? 'desc' : 'asc';

        $allowedSorts = ['email', 'quota_mb', 'used_mb', 'pct'];
        if (!in_array($sort, $allowedSorts, true)) {
            $sort = 'email';
        }

        $accounts = MailAccount::with('domain')->get()->map(function (MailAccount $account) {
            $usedMb = $this->diskUsageMb($account->email);
            $quotaMb = $account->quota_mb;
            $pct = ($quotaMb > 0 && $usedMb !== null) ? min(100, round($usedMb / $quotaMb * 100)) : null;

            return [
                'account' => $account,
                'used_mb' => $usedMb,
                'pct'     => $pct,
            ];
        });

        // Sort client-side (already fetched all records)
        $accounts = $accounts->sortBy(function ($row) use ($sort) {
            return match ($sort) {
                'quota_mb' => $row['account']->quota_mb ?? PHP_INT_MAX,
                'used_mb'  => $row['used_mb'] ?? -1,
                'pct'      => $row['pct'] ?? -1,
                default    => $row['account']->email,
            };
        }, SORT_REGULAR, $dir === 'desc');

        return view(mailView('admin.accounts.usage'), [
            'rows'  => $accounts->values(),
            'sort'  => $sort,
            'dir'   => $dir,
        ]);
    }

    private function diskUsageMb(string $email): ?float
    {
        $vhostsPath = rtrim(config('mail.vhosts_path', ''), '/');
        if ($vhostsPath === '') {
            return null;
        }

        [$local, $domain] = explode('@', $email, 2);
        $path = "{$vhostsPath}/{$domain}/{$local}";

        // Sanitise path: only allow safe characters to prevent command injection
        if (!preg_match('#^[a-zA-Z0-9/_\-\.@]+$#', $path)) {
            return null;
        }

        if (!is_dir($path)) {
            return null;
        }

        $output = [];
        $code   = 0;
        exec('du -sm ' . escapeshellarg($path) . ' 2>/dev/null', $output, $code);

        if ($code !== 0 || empty($output)) {
            return null;
        }

        $parts = preg_split('/\s+/', trim($output[0]));
        $mb    = isset($parts[0]) ? (float) $parts[0] : null;

        return ($mb !== null && $mb >= 0) ? $mb : null;
    }
}
